### ISSUE TITLE
NanoEventsFactory.from_parquet triggers a TypeError in delayed mode when events is called

### ISSUE THREAD

**Issue by NJManganelli** [scikit-hep/coffea#1010]
**Describe the bug**
calling `events()` on `NanoEventsFactory.from_parquet(filename, delayed=False)` works okay, but with `delayed=True,' it triggers an unexpected code path/error:

**To Reproduce**
```
# with coffea.__version__ == '2024.1.2'
import coffea
from coffea.nanoevents import NanoEventsFactory, NanoAODSchema
fname = "/afs/cern.ch/user/n/nmangane/public/part00.parquet"
pqe = NanoEventsFactory.from_parquet(fname, delayed=False)
pqe.events().fields
#output:['FatJet', 'L1Reco', 'SoftActivityJetHT5', 'SoftActivityJetHT10', 'Flag', 'LHEPart', 'SoftActivityJetNjets10', 'OtherPV', 'luminosityBlock', 'Jet', 'genWeight', 'PSWeight', 'fixedGridRhoFastjetCentralCalo', 'GenMET', 'HTXS', 'GenDressedLepton', 'SoftActivityJetNjets2', 'PV', 'SV', 'Muon', 'SoftActivityJetHT', 'fixedGridRhoFastjetCentralNeutral', 'L1simulation', 'PuppiMET', 'btagWeight', 'genTtbarId', 'GenJetAK8', 'HLTriggerFinalPath', 'DeepMETResponseTune', 'FsrPhoton', 'fixedGridRhoFastjetCentral', 'fixedGridRhoFastjetAll', 'Pileup', 'SoftActivityJetNjets5', 'LHEReweightingWeight', 'HLTriggerFirstPath', 'LHEPdfWeight', 'HLT', 'Generator', 'GenPart', 'RawMET', 'RawPuppiMET', 'Photon', 'MET', 'event', 'fixedGridRhoFastjetCentralChargedPileUp', 'CorrT1METJet', 'DeepMETResolutionTune', 'Tau', 'CaloMET', 'LHEScaleWeight', 'run', 'ChsMET', 'GenJet', 'LHEWeight', 'SoftActivityJetHT2', 'GenIsolatedPhoton', 'TkMET', 'GenVisTau', 'Electron', 'SoftActivityJet', 'LHE']
pqd = NanoEventsFactory.from_parquet(fname, delayed=True)
pqd.events()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/srv/.env/lib/python3.11/site-packages/coffea/nanoevents/factory.py", line 674, in events
    events = self._mapping(form_mapping=self._schema)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: from_parquet() got an unexpected keyword argument 'form_mapping'
```
**Expected behavior**
Produced form_mapped dask-awkward array

**Comment by lgray** [comment]
This is not yet supported in coffea 2023. Form remapping needs to be implemented for dak.from_parquet. Only root input is available at present in delayed mode.

**Comment by NJManganelli** [comment]
I'll need to open a separate issue or PR later (...), but a follow up on this with newer software versions has the misfortune of breaking the non-delayed path

To document, the first error that will pop up is failing to get the dtype 
```
---------------------------------------------------------------------------
NotImplementedError                       Traceback (most recent call last)
Cell In[85], line 4
      2 from coffea.nanoevents import NanoEventsFactory, NanoAODSchema
      3 fnameraw = "[~/Downloads/cmsopendata2015_ttbar_19980_PU25nsData2015v1_76X_mcRun2_asymptotic_v12_ext3-v1_00000_0005.parquet](http://localhost:8888/lab/tree/~/Downloads/cmsopendata2015_ttbar_19980_PU25nsData2015v1_76X_mcRun2_asymptotic_v12_ext3-v1_00000_0005.parquet)"
----> 4 e = NanoEventsFactory.from_parquet(fnameraw, schemaclass=NanoAODSchema, delayed=False).events()

File [~/scikit-hep-dev-pixi/.pixi/envs/default/lib/python3.12/site-packages/coffea/nanoevents/factory.py:551](http://localhost:8888/lab/tree/~/scikit-hep-dev-pixi/.pixi/envs/default/lib/python3.12/site-packages/coffea/nanoevents/factory.py#line=550), in NanoEventsFactory.from_parquet(cls, file, treepath, entry_start, entry_stop, runtime_cache, persistent_cache, schemaclass, metadata, parquet_options, skyhook_options, access_log, delayed)
    545     shim = TrivialParquetOpener.UprootLikeShim(
    546         table_file, dataset, openfile=fs_file
    547     )
    549 mapping.preload_column_source(partition_key[0], partition_key[1], shim)
--> 551 base_form = mapping._extract_base_form(table_file.schema_arrow)
    553 return cls._from_mapping(
    554     mapping,
    555     partition_key,
   (...)
    560     metadata,
    561 )

File [~/scikit-hep-dev-pixi/.pixi/envs/default/lib/python3.12/site-packages/coffea/nanoevents/mapping/parquet.py:158](http://localhost:8888/lab/tree/~/scikit-hep-dev-pixi/.pixi/envs/default/lib/python3.12/site-packages/coffea/nanoevents/mapping/parquet.py#line=157), in ParquetSourceMapping._extract_base_form(cls, arrow_schema)
    156     print("field.type", type(field.type), field.type)
    157     schema = field.type
--> 158     form = arrow_schema_to_awkward_form(schema)
    159     form = json.loads(form.to_json())
    161 if (
    162     form["class"].startswith("ListOffset")
    163     and form["content"]["class"] == "NumpyArray"  # noqa
    164 ):

File [~/scikit-hep-dev-pixi/.pixi/envs/default/lib/python3.12/site-packages/coffea/nanoevents/mapping/parquet.py:85](http://localhost:8888/lab/tree/~/scikit-hep-dev-pixi/.pixi/envs/default/lib/python3.12/site-packages/coffea/nanoevents/mapping/parquet.py#line=84), in arrow_schema_to_awkward_form(schema)
     83 elif isinstance(schema, pa.lib.DataType):
     84     print("schema:", schema)
---> 85     dtype = schema.to_pandas_dtype()()
     86     return awkward.forms.NumpyForm(
     87         inner_shape=[],
     88         primitive=dtype.dtype.name,
     89     )
     90 else:

File [~/scikit-hep-dev-pixi/.pixi/envs/default/lib/python3.12/site-packages/pyarrow/types.pxi:406](http://localhost:8888/lab/tree/~/scikit-hep-dev-pixi/.pixi/envs/default/lib/python3.12/site-packages/pyarrow/types.pxi#line=405), in pyarrow.lib.DataType.to_pandas_dtype()

File [~/scikit-hep-dev-pixi/.pixi/envs/default/lib/python3.12/site-packages/pyarrow/types.pxi:195](http://localhost:8888/lab/tree/~/scikit-hep-dev-pixi/.pixi/envs/default/lib/python3.12/site-packages/pyarrow/types.pxi#line=194), in pyarrow.lib._to_pandas_dtype()

NotImplementedError: ak:uint32
```
See closed awkward issue:
https://github.com/scikit-hep/awkward/issues/3393

attempted fix: modify this code with a try-except block (some types appear to wrap LargeListTypes that would take the upper code path instead... and that path may also be desirable/necessary to add a `storage_type` call after the `value_type`). 
```

    elif isinstance(schema, pa.lib.DataType):
        try:
            dtype = schema.storage_type.to_pandas_dtype()()
        except:
            # awkward<LargeListType(large_list<item: extension<awkward<AwkwardArrowType>> not null>)>
            dtype = schema.storage_type.value_type.storage_type.to_pandas_dtype()()
        return awkward.forms.NumpyForm(
            inner_shape=[],
            primitive=dtype.dtype.name,
        )
```

Then, one can see a failure in the local2global_form call due to the first input, `index` being a `NumpyArray` type rather than one of the `ListOffset`... types. Comparing the root file opening vs parquet, one can see the following when printing out index and target_offsets of a field that triggers this, e.g. `Electron_genPartIdx`. 

```
def local2global_form(index, target_offsets):
    if not index["class"].startswith("ListOffset"):
        raise RuntimeError
```

```
e = NanoEventsFactory.from_root({fnameraw.replace("parquet", "root"):"Events"}, schemaclass=NanoAODSchema, delayed=False)

{'class': 'ListOffsetArray', 'offsets': 'i64', 'content': {'class': 'NumpyArray', 'primitive': 'int32', 'inner_shape': [], 'parameters': {'__doc__': 'Index into genParticle list for MC matching to status==1 electrons or photons'}, 'form_key': 'Electron_genPartIdx%2C%21load%2C%21content'}, 'parameters': {}, 'form_key': 'Electron_genPartIdx%2C%21load'}
{'class': 'NumpyArray', 'itemsize': 8, 'format': 'i', 'primitive': 'int64', 'parameters': {'__doc__': 'interesting gen particles '}, 'form_key': 'nGenPart%2C%21load%2C%21counts2offsets'}
```

```
e = NanoEventsFactory.from_parquet(fnameraw, schemaclass=NanoAODSchema, delayed=False)

{'class': 'NumpyArray', 'primitive': 'int32', 'inner_shape': [], 'parameters': {'__doc__': 'Electron_genPartIdx'}, 'form_key': 'Electron_genPartIdx%2C%21load'}
{'class': 'NumpyArray', 'itemsize': 8, 'format': 'i', 'primitive': 'int64', 'parameters': {'__doc__': 'nGenPart'}, 'form_key': 'nGenPart%2C%21load%2C%21counts2offsets'}
```

EDIT: So probably need to fix the datatype identification with some recursion, so a ListOffsetArray is the result

**Comment by NJManganelli** [comment]
Discard the above comment, errors regarding dtype and downstream were triggered by some seemingly-malformed parquet file I have in my possession (which is related to a problematic root file I once used as a source for tests and currently cannot even convert with `hepconvert` anymore due to pyarrow errors). Explicitly testing different files made with extensionarray both True and False, that particular block of code seems to work fine and produce appropriate layouts with either option. Downstream of that the shim for loading might need some small updates...

**Comment by nsmith-** [comment]
Related to #1273
