### ISSUE TITLE
OSError not handled when running over normalized fileset

### ISSUE THREAD

**Issue by JaLuka98** [scikit-hep/coffea#1039]
**Describe the bug**
Running some analysis code works when scaling out on a single machine, but it crashes with some xrootd errors when scaling out to htcondor via dask.

**To Reproduce**
1. Be in CMS.
2. Run https://gitlab.cern.ch/cms-cat/zmumu-cross-section/-/blob/2-extend-ntupliser-with-dask-htcondor-scale-out-functionality/sample_processing/NTupliser.py?ref_type=heads after devising a sample JSON with the appropriate helper files in the same repo. Make sure to run with the htcondor scale out (commented out in the branch as it does not work).
3. See it crash...

**Expected behavior**
It works when scaling out on a single machine, so it is confusing that it crashes when scaling out with htcondor. This should not happen. It might be related to the CMS grid proxy.

**Output**
Two traces are attached.
[error_skipbadfilesTrue.txt](https://github.com/CoffeaTeam/coffea/files/14283573/error_skipbadfilesTrue.txt)
[error_skipbadfilesFalse.txt](https://github.com/CoffeaTeam/coffea/files/14283574/error_skipbadfilesFalse.txt)

**Desktop (please complete the following information):**
 - EL9
 - coffea '2024.2.1'
 - xrootd '5.6.4'
 - fsspec-xrootd '0.2.3'
 - dask '2023.12.1'
 - dask_jobqueue '0.8.2'
 - distributed '2023.12.1'
- awkward '2.6.1'
- uproot '5.2.2'

**Additional context**
None

**Comment by JaLuka98** [comment]
FYI @lgray

**Comment by lgray** [comment]
Can you put the stack trace here? @JaLuka98

**Comment by JaLuka98** [comment]
Yes, sure @lgray
I put them as attachment to the original post, but I can paste, no problem.

With `skip_bad_files=False` in `preprocess`:
```
Traceback (most recent call last):
  File "/.automount/net_rw/net__scratch_cms3a/spaeh/public/PhD/CAT/zmumu-cross-section/sample_processing/NTupliser.py", line 161, in <module>
    futures = dask.compute(to_compute) # futures: represent the ongoing or completed computations within the Dask cluster, regardless of the underlying execution environment
  File "/.automount/home/home__home1/institut_3a/spaeh/micromamba/envs/coffea_2023_env/lib/python3.10/site-packages/dask/base.py", line 628, in compute
    results = schedule(dsk, keys, **kwargs)
  File "/.automount/home/home__home1/institut_3a/spaeh/micromamba/envs/coffea_2023_env/lib/python3.10/site-packages/uproot/_dask.py", line 1256, in __call__
    return self._call_impl(
  File "/.automount/home/home__home1/institut_3a/spaeh/micromamba/envs/coffea_2023_env/lib/python3.10/site-packages/uproot/_dask.py", line 1184, in _call_impl
    ttree = uproot._util.regularize_object_path(
  File "/.automount/home/home__home1/institut_3a/spaeh/micromamba/envs/coffea_2023_env/lib/python3.10/site-packages/uproot/_util.py", line 962, in regularize_object_path
    file = ReadOnlyFile(
  File "/.automount/home/home__home1/institut_3a/spaeh/micromamba/envs/coffea_2023_env/lib/python3.10/site-packages/uproot/reading.py", line 559, in __init__
    self._source = source_cls(file_path, **self._options)
  File "/.automount/home/home__home1/institut_3a/spaeh/micromamba/envs/coffea_2023_env/lib/python3.10/site-packages/uproot/source/fsspec.py", line 41, in __init__
    self._open()
  File "/.automount/home/home__home1/institut_3a/spaeh/micromamba/envs/coffea_2023_env/lib/python3.10/site-packages/uproot/source/fsspec.py", line 55, in _open
    self._file = self._fs.open(self._file_path)
  File "/.automount/home/home__home1/institut_3a/spaeh/micromamba/envs/coffea_2023_env/lib/python3.10/site-packages/fsspec_xrootd/xrootd.py", line 597, in open
    f = self._open(
  File "/.automount/home/home__home1/institut_3a/spaeh/micromamba/envs/coffea_2023_env/lib/python3.10/site-packages/fsspec_xrootd/xrootd.py", line 554, in _open
    return XRootDFile(
  File "/.automount/home/home__home1/institut_3a/spaeh/micromamba/envs/coffea_2023_env/lib/python3.10/site-packages/fsspec_xrootd/xrootd.py", line 660, in __init__
    raise OSError(f"File did not open properly: {status.message}")
OSError: File did not open properly: [ERROR] Server responded with an error: [3011] No servers are available to read the file.
```
With `skip_bad_files=True` in `preprocess`:
```
Traceback (most recent call last):
  File "/.automount/net_rw/net__scratch_cms3a/spaeh/public/PhD/CAT/zmumu-cross-section/sample_processing/NTupliser.py", line 161, in <module>
    futures = dask.compute(to_compute) # futures: represent the ongoing or completed computations within the Dask cluster, regardless of the underlying execution environment
  File "/.automount/home/home__home1/institut_3a/spaeh/micromamba/envs/coffea_2023_env/lib/python3.10/site-packages/dask/base.py", line 628, in compute
    results = schedule(dsk, keys, **kwargs)
  File "/.automount/home/home__home1/institut_3a/spaeh/micromamba/envs/coffea_2023_env/lib/python3.10/site-packages/uproot/_dask.py", line 1256, in __call__
    return self._call_impl(
  File "/.automount/home/home__home1/institut_3a/spaeh/micromamba/envs/coffea_2023_env/lib/python3.10/site-packages/uproot/_dask.py", line 1184, in _call_impl
    ttree = uproot._util.regularize_object_path(
  File "/.automount/home/home__home1/institut_3a/spaeh/micromamba/envs/coffea_2023_env/lib/python3.10/site-packages/uproot/_util.py", line 962, in regularize_object_path
    file = ReadOnlyFile(
  File "/.automount/home/home__home1/institut_3a/spaeh/micromamba/envs/coffea_2023_env/lib/python3.10/site-packages/uproot/reading.py", line 559, in __init__
    self._source = source_cls(file_path, **self._options)
  File "/.automount/home/home__home1/institut_3a/spaeh/micromamba/envs/coffea_2023_env/lib/python3.10/site-packages/uproot/source/fsspec.py", line 41, in __init__
    self._open()
  File "/.automount/home/home__home1/institut_3a/spaeh/micromamba/envs/coffea_2023_env/lib/python3.10/site-packages/uproot/source/fsspec.py", line 55, in _open
    self._file = self._fs.open(self._file_path)
  File "/.automount/home/home__home1/institut_3a/spaeh/micromamba/envs/coffea_2023_env/lib/python3.10/site-packages/fsspec_xrootd/xrootd.py", line 597, in open
    f = self._open(
  File "/.automount/home/home__home1/institut_3a/spaeh/micromamba/envs/coffea_2023_env/lib/python3.10/site-packages/fsspec_xrootd/xrootd.py", line 554, in _open
    return XRootDFile(
  File "/.automount/home/home__home1/institut_3a/spaeh/micromamba/envs/coffea_2023_env/lib/python3.10/site-packages/fsspec_xrootd/xrootd.py", line 660, in __init__
    raise OSError(f"File did not open properly: {status.message}")
OSError: File did not open properly: [ERROR] Server responded with an error: [3011] No servers are available to read the file.
```

**Comment by lgray** [comment]
So another interesting thing here is that *none* of this is happening in preprocess. :-)

**Comment by lgray** [comment]
So the error is coming from here:
https://gitlab.cern.ch/cms-cat/zmumu-cross-section/-/blob/2-extend-ntupliser-with-dask-htcondor-scale-out-functionality/sample_processing/NTupliser.py?ref_type=heads#L146-152

raised on L163 when you compute it. Preprocess is going fine, the error is not being caught in uproot.

**Comment by lgray** [comment]
Ah - this is already fixed. You need to pass: `uproot_options={"allow_read_errors_with_report": True}` and then you'll get a file-opening-failure report and all failures will be skipped.

**Comment by lgray** [comment]
Closing as this is already fixed. However it indicates a need to improve the documentation.
