### ISSUE TITLE
Unclear exception with processing dataset with no events

### ISSUE THREAD

**Issue by alexander-held** [scikit-hep/coffea#1141]
**Describe the bug**
When a dataset (out of `dataset_tools.preprocess`) has zero chunks to run over, `dataset_tools.apply_to_fileset` will raise `FileNotFoundError` on `{}`. I think this usually happens when some other more serious thing has gone wrong at first but I occasionally see people run into this and it's not immediately obvious what happened.

**To Reproduce**
the following makes use of a fix for #1140 to run:
```python
import uproot
import awkward as ak
from coffea import dataset_tools
from coffea.nanoevents import BaseSchema
import dask

with uproot.recreate("f1.root") as f:
   f["tree"] = {"arr": ak.Array([])}
with uproot.recreate("f2.root") as f:
   f["tree"] = {"arr": ak.Array([1])}

fileset = {"dummy": {"files": {"f1.root": "tree"}}}
# fileset = {"dummy": {"files": {"f1.root": "tree", "f2.root": "tree"}}}  # this works
samples, _ = dataset_tools.preprocess(fileset)
tasks = dataset_tools.apply_to_fileset(lambda evts: None, samples, schemaclass=BaseSchema)
_ = dask.compute(tasks)
```

**Expected behavior**
A warning along the lines of "no useable files found for dataset xyz" and no exception raised by default.

**Output**
```pytb
Traceback (most recent call last):
  File "[...]]/test.py", line 17, in <module>
    tasks = dataset_tools.apply_to_fileset(lambda evts: None, samples, schemaclass=BaseSchema)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "[...]/coffea/dataset_tools/apply_processor.py", line 125, in apply_to_fileset
    dataset_out = apply_to_dataset(
                  ^^^^^^^^^^^^^^^^^
  File "[...]/coffea/dataset_tools/apply_processor.py", line 73, in apply_to_dataset
    ).events()
      ^^^^^^^^
  File "[...]/coffea/nanoevents/factory.py", line 684, in events
    events = self._mapping(form_mapping=self._schema)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "[...]/uproot/_dask.py", line 183, in dask
    files = uproot._util.regularize_files(files, steps_allowed=True, **options)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "[...]/uproot/_util.py", line 946, in regularize_files
    raise _file_not_found(files)
FileNotFoundError: file not found

    {}

Files may be specified as:
   * str/bytes: relative or absolute filesystem path or URL, without any colons
         other than Windows drive letter or URL schema.
         Examples: "rel/file.root", "C:\abs\file.root", "http://where/what.root"
   * str/bytes: same with an object-within-ROOT path, separated by a colon.
         Example: "rel/file.root:tdirectory/ttree"
   * pathlib.Path: always interpreted as a filesystem path or URL only (no
         object-within-ROOT path), regardless of whether there are any colons.
         Examples: Path("rel:/file.root"), Path("/abs/path:stuff.root")

Functions that accept many files (uproot.iterate, etc.) also allow:
   * glob syntax in str/bytes and pathlib.Path.
         Examples: Path("rel/*.root"), "/abs/*.root:tdirectory/ttree"
   * dict: keys are filesystem paths, values are objects-within-ROOT paths.
         Example: {"/data_v1/*.root": "ttree_v1", "/data_v2/*.root": "ttree_v2"}
   * already-open TTree objects.
   * iterables of the above.
```

**Desktop (please complete the following information):**
n/a

**Additional context**
n/a

**Comment by lgray** [comment]
Technically the error is correct, if the list is empty it does not conform to that spec! 

We can make a more clear error with some suggestions for improving the situation.

**Comment by ikrommyd** [comment]
This appears to have changed since it was reported. It now fails during preprocessing and not execution but with a rather cryptic error.
```
---------------------------------------------------------------------------
ZeroDivisionError                         Traceback (most recent call last)
Cell In[1], line 14
     12 fileset = {"dummy": {"files": {"f1.root": "tree"}}}
     13 # fileset = {"dummy": {"files": {"f1.root": "tree", "f2.root": "tree"}}}  # this works
---> 14 samples, _ = dataset_tools.preprocess(fileset, skip_bad_files=True)

File ~/Dropbox/work/pyhep_dev/coffea/src/coffea/dataset_tools/preprocess.py:354, in preprocess(fileset, step_size, align_clusters, recalculate_steps, files_per_batch, skip_bad_files, file_exceptions, save_form, scheduler, uproot_options, step_size_safety_factor, allow_empty_datasets)
    343     files_graph = dask.highlevelgraph.HighLevelGraph.from_collections(
    344         files_trl_name, files_trl, dependencies=[files_part]
    345     )
    347     files_to_preprocess[name] = dask_awkward.lib.core.new_array_object(
    348         files_graph,
    349         files_trl_name,
    350         meta=dask_awkward.lib.core.empty_typetracer(),
    351         npartitions=len(files_trl.output_partitions),
    352     )
--> 354 (all_processed_files,) = dask.compute(files_to_preprocess, scheduler=scheduler)
    356 for name, processed_files in all_processed_files.items():
    358     if len(awkward.drop_none(processed_files, axis=0)) == 0:

File ~/micromamba/envs/awkward-coffea/lib/python3.13/site-packages/dask/base.py:656, in compute(traverse, optimize_graph, scheduler, get, *args, **kwargs)
    653     postcomputes.append(x.__dask_postcompute__())
    655 with shorten_traceback():
--> 656     results = schedule(dsk, keys, **kwargs)
    658 return repack([f(r, *a) for r, (f, a) in zip(results, postcomputes)])

File ~/Dropbox/work/pyhep_dev/coffea/src/coffea/dataset_tools/preprocess.py:134, in get_steps(normed_files, step_size, align_clusters, recalculate_steps, skip_bad_files, file_exceptions, save_form, step_size_safety_factor, uproot_options)
    127         warnings.warn(
    128             f"In file {arg.file}, steps: {out[step_mask]} with align_clusters=True are "
    129             f"{step_size_safety_factor*100:.0f}% larger than target "
    130             f"step size: {target_step_size}!"
    131         )
    133 else:
--> 134     n_steps_target = max(round(num_entries / target_step_size), 1)
    135     actual_step_size = math.ceil(num_entries / n_steps_target)
    136     out = numpy.array(
    137         [
    138             [
   (...)    144         dtype="int64",
    145     )

ZeroDivisionError: division by zero
```

**Comment by ikrommyd** [comment]
Also the other line that Alex originally claimed to be working fails with the same thing now
```
fileset = {"dummy": {"files": {"f1.root": "tree", "f2.root": "tree"}}}  # this works
```
