### ISSUE TITLE
Error When Loading Column-Trimmed Root Files Using NanoEvents

### ISSUE THREAD

**Issue by kapsiak** [scikit-hep/coffea#1147]
**Describe the bug**

Reading root files which have been saved using the prescription  https://github.com/CoffeaTeam/coffea/discussions/735#discussioncomment-9646917 with column-filtering cannot be loaded by `NanoEventsFactory` using `NanoAODSchema`.  Depending on the saved fields, the following exception is thrown:

``` 
TypeError: do not try to convert low-level layouts (Content subclasses) into NumPy arrays; put them in ak.highlevel.Array
```

The stack trace is quite deep and can be generated with the below example. 

**To Reproduce**

Below is a small example script that demonstrates the behavior, where an exception is raised when trying to load the 
```python
import awkward as ak
import uproot
from coffea.nanoevents import NanoEventsFactory

def is_rootcompat(a):
    """Is it a flat or 1-d jagged array?"""
    t = ak.type(a)
    if isinstance(t, ak.types.ArrayType):
        if isinstance(t.content, ak.types.NumpyType):
            return True
        if isinstance(t.content, ak.types.ListType) and isinstance(t.content.content, ak.types.NumpyType):
            return True
    return False

def uproot_writeable(events):
    """Restrict to columns that uproot can write compactly"""
    out = {}
    for bname in events.fields:
        if events[bname].fields:
            out[bname] = ak.zip({n: 
                                 ak.to_packed(ak.without_parameters(events[bname][n])) 
                                 for n in events[bname].fields 
                                 if is_rootcompat(events[bname][n])}, 
                               )
        else:  
            out[bname] = ak.to_packed(ak.without_parameters(events[bname]))
    return out


filename = "https://raw.githubusercontent.com/CoffeaTeam/coffea/master/tests/samples/nano_dy.root"
events = NanoEventsFactory.from_root({filename: "Events"}, delayed=False).events()

def saveAndLoad(events, columns):  
    filtered_events = events[columns]
    with uproot.recreate("skimmedevents.root") as fout:
        fout["Events"] = uproot_writeable(filtered_events)
    reloaded = NanoEventsFactory.from_root({"skimmedevents.root": "Events"}, delayed=False).events()
    print(reloaded.fields)

# This works
saveAndLoad(events, events.fields)
 # This works
saveAndLoad(events, ["event", "run",  "luminosityBlock"])
 # This works
saveAndLoad(events, ["event", "run",  "luminosityBlock", "Electron", "Muon", "HLT"])
 # This does not work
saveAndLoad(events, ["event", "run",  "luminosityBlock", "Electron", "Jet"])
```

**Expected behavior**

It is expected that column-trimmed files should be able to be loaded by `NanoEventsFactory` and have the same content and cross-references where possible. 

**Version Info**
```
coffea: 2024.6.1
awkward: 2.6.5
uproot: 5.3.10
```

**Comment by nsmith-** [comment]
Full stack trace:
```
Traceback (most recent call last):
  File "/Users/ncsmith/src/coffea/test_issue1147.py", line 57, in <module>
    saveAndLoad(events, ["event", "run", "luminosityBlock", "Electron", "Jet"])
    ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ncsmith/src/coffea/test_issue1147.py", line 46, in saveAndLoad
    ).events()
      ~~~~~~^^
  File "/Users/ncsmith/src/coffea/src/coffea/nanoevents/factory.py", line 807, in events
    events = awkward.from_buffers(
        form=form,
    ...<12 lines>...
        },
    )
  File "/Users/ncsmith/src/coffea/.venv/lib/python3.13/site-packages/awkward/_dispatch.py", line 41, in dispatch
    with OperationErrorContext(name, args, kwargs):
         ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
  File "/Users/ncsmith/src/coffea/.venv/lib/python3.13/site-packages/awkward/_errors.py", line 80, in __exit__
    raise self.decorate_exception(exception_type, exception_value)
  File "/Users/ncsmith/src/coffea/.venv/lib/python3.13/site-packages/awkward/_dispatch.py", line 42, in dispatch
    gen_or_result = func(*args, **kwargs)
  File "/Users/ncsmith/src/coffea/.venv/lib/python3.13/site-packages/awkward/operations/ak_from_buffers.py", line 110, in from_buffers
    return _impl(
        form,
    ...<8 lines>...
        allow_noncanonical_form,
    )
  File "/Users/ncsmith/src/coffea/.venv/lib/python3.13/site-packages/awkward/operations/ak_from_buffers.py", line 157, in _impl
    out = _reconstitute(
        form,
    ...<7 lines>...
        shape_generator=lambda: (length,),
    )
  File "/Users/ncsmith/src/coffea/.venv/lib/python3.13/site-packages/awkward/operations/ak_from_buffers.py", line 624, in _reconstitute
    _reconstitute(
    ~~~~~~~~~~~~~^
        content,
        ^^^^^^^^
    ...<7 lines>...
        shape_generator,
        ^^^^^^^^^^^^^^^^
    )
    ^
  File "/Users/ncsmith/src/coffea/.venv/lib/python3.13/site-packages/awkward/operations/ak_from_buffers.py", line 576, in _reconstitute
    content = _reconstitute(
        form.content,
    ...<7 lines>...
        _shape_generator,
    )
  File "/Users/ncsmith/src/coffea/.venv/lib/python3.13/site-packages/awkward/operations/ak_from_buffers.py", line 624, in _reconstitute
    _reconstitute(
    ~~~~~~~~~~~~~^
        content,
        ^^^^^^^^
    ...<7 lines>...
        shape_generator,
        ^^^^^^^^^^^^^^^^
    )
    ^
  File "/Users/ncsmith/src/coffea/.venv/lib/python3.13/site-packages/awkward/operations/ak_from_buffers.py", line 548, in _reconstitute
    raw_array = container[getkey(form, "offsets")]
                ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ncsmith/src/coffea/src/coffea/nanoevents/mapping/base.py", line 146, in __getitem__
    return _getitem(key)
  File "/Users/ncsmith/src/coffea/src/coffea/nanoevents/mapping/base.py", line 123, in _getitem
    getattr(transforms, tname)(stack)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^
  File "/Users/ncsmith/src/coffea/src/coffea/nanoevents/transforms.py", line 467, in nestedindex
    out[i::n] = idx
    ~~~^^^^^^
  File "/Users/ncsmith/src/coffea/.venv/lib/python3.13/site-packages/awkward/contents/content.py", line 310, in __array__
    raise TypeError(
        "do not try to convert low-level layouts (Content subclasses) into NumPy arrays; put them in ak.highlevel.Array"
    )
TypeError: do not try to convert low-level layouts (Content subclasses) into NumPy arrays; put them in ak.highlevel.Array

This error occurred while calling

    ak.from_buffers(
        form = {'class': 'RecordArray', 'fields': ['Electron', 'event', 'lumi...
        length = 40
        container = <coffea.nanoevents.mapping.uproot.UprootSourceMapping obj...
        buffer_key = partial-instance
        backend = 'cpu'
        byteorder = '<'
        allow_noncanonical_form = False
        highlevel = True
        behavior = {'Systematic': <class 'coffea.nanoevents.methods.base.Syst...
        attrs = {'@events_factory': <coffea.nanoevents.factory.NanoEventsFact...
    )
```
