### ISSUE TITLE
Understand applicability of FAST aggregate data manipulations in coffea and spark

### ISSUE THREAD

**Issue by lgray** [scikit-hep/coffea#187]
More from talking to @benkrikler:
- FAST has developed a very interesting pandas-based implementation of multidimensional sparse histograms in pandas
- They cover most of the operations that are in coffea histograms and we'd like to understand if they are valid spark dataframes in addition to pandas. 
- We will proceed by first doing tests of passing some self-generated fast histograms into spark 

If this works out it could be a huge improvement in the case of using spark (since we no longer blob histograms) and give the first case of trying multiple histogram libraries within coffea. 

The latter bit should be an interesting first foray into how to deal with multiple histogram packages well. We should maybe try boost histogram too?

This is a tracking issue for this feature.

**Comment by lgray** [comment]
Hmm. First tests run quickly into problems:

```
Traceback (most recent call last):
  File "coffea_glue.py", line 127, in <module>
    df = spark.createDataFrame(sparklypds)
  File "/anaconda3/envs/fastcarpenter/lib/python3.6/site-packages/pyspark/sql/session.py", line 748, in createDataFrame
    rdd, schema = self._createFromLocal(map(prepare, data), schema)
  File "/anaconda3/envs/fastcarpenter/lib/python3.6/site-packages/pyspark/sql/session.py", line 416, in _createFromLocal
    struct = self._inferSchemaFromList(data, names=schema)
  File "/anaconda3/envs/fastcarpenter/lib/python3.6/site-packages/pyspark/sql/session.py", line 348, in _inferSchemaFromList
    schema = reduce(_merge_type, (_infer_schema(row, names) for row in data))
  File "/anaconda3/envs/fastcarpenter/lib/python3.6/site-packages/pyspark/sql/session.py", line 348, in <genexpr>
    schema = reduce(_merge_type, (_infer_schema(row, names) for row in data))
  File "/anaconda3/envs/fastcarpenter/lib/python3.6/site-packages/pyspark/sql/types.py", line 1064, in _infer_schema
    fields = [StructField(k, _infer_type(v), True) for k, v in items]
  File "/anaconda3/envs/fastcarpenter/lib/python3.6/site-packages/pyspark/sql/types.py", line 1064, in <listcomp>
    fields = [StructField(k, _infer_type(v), True) for k, v in items]
  File "/anaconda3/envs/fastcarpenter/lib/python3.6/site-packages/pyspark/sql/types.py", line 1038, in _infer_type
    raise TypeError("not supported type: %s" % type(obj))
TypeError: not supported type: <class 'pandas._libs.interval.Interval'>
```

Might be updated in spark3?

Will attempt workaround.

**Comment by lgray** [comment]
Looks like you can stringify it.

**Comment by lgray** [comment]
Yeah, so turning the ranges into strings allows one to go in and out of spark, and resetting the indices back to the columns is easy with pandas.

The more sticky part seems to be turning the index-as-column back into an index since the intermediate format of the indices are strings. However the loop back into an pandas.IntervalIndex / CategoricalIndex can be done:

```python
import pandas as pd
# here we have run FAST carpenter in coffea and have ended up with a bunch of filled stages
# first turn the index into strings, the index name here is dimu_mass for example
sparklypds = out['stages']['wjets'][4].contents.rename(index=str)
# turn the index back into a regular column so we can save it in spark
sparklypds.reset_index(drop=False, inplace=True)
# let's go to space
df = spark.createDataFrame(sparklypds)
# space too big, wanna go back to earth
pdsout = df.select('*').toPandas()
# now to convert the index back into intervals and categories
temp = pdsout['dimu_mass'].str.replace(' ', '') \
                          .str.strip('[)') \
                          .str.split(',', expand=True) \
                          .apply(pd.to_numeric)
idx = pd.IntervalIndex.from_arrays(left=temp[0], right=temp[1], closed='left')
idx = pd.CategoricalIndex(data=idx, ordered=True)
# replace the column with the index
pdsout['dimu_mass'] = idx
# turn the index into the df's index, drop the columns that were formerly the index
pdsout.set_index('dimu_mass', inplace=True, drop=True)
```

results in:
```
>>> check = (pdsout == out['stages']['wjets'][4].contents)
>>> check['n'].all()
True
>>> check['weighted:sumw'].all()
True
>>> check['weighted:sumw2'].all()
True
```

So probably with only a little bit of unpleasantness we can operate on pandas-based histograms in spark (through a couple of UDFs and some string manipulation on either side of going in/out of spark).

@jpivarski

**Comment by lgray** [comment]
A few more additions and I can now reconstruct any numerical MultiIndex.
Trying to find some examples of histograms in FAST with string axes and such (@benkrikler?).

It's a bit kludgey since you need to postfix everything with `_IDX` or some identifier, but again, it works so far.

**Comment by lgray** [comment]
Eventually I'll stick this in a gist, but for now just tracking things here as I hack.
```python
idx_postfix = 'IDX'
idx_names = out['stages']['wjets'][2].contents.index.names
sparklypds = out['stages']['wjets'][2].contents.rename(index=str)

sparklypds.reset_index(drop=False,inplace=True)
sparklypds.rename(columns = {name: name+'_'+idx_postfix for name in idx_names}, inplace=True)

print(sparklypds)

df = spark.createDataFrame(sparklypds)

pdsout = df.select('*').toPandas()

index_cols = pdsout.filter(regex='_IDX')
for name in idx_names:
    fullname = name + '_' + idx_postfix
    temp = index_cols[fullname].str.replace(' ','') \
            .str.strip('[)') \
            .str.split(',', expand=True)
    # try to turn this into a numerical index, otherwise pass through
    try:
        temp = temp.apply(pd.to_numeric)
    except ValueError:
        pass

    idx = None
    if len(temp.columns) == 2:
        # this is an interval index (bins)
        idx = pd.IntervalIndex.from_arrays(left=temp[0],right=temp[1],closed='left')
        idx = pd.CategoricalIndex(data=idx, ordered=True)
    else:
        # this is some other numerical index
        idx = pd.Index(temp.squeeze())

    pdsout[fullname] = idx
pdsout.rename(columns={name+'_'+idx_postfix: name for name in idx_names}, inplace=True)
pdsout.set_index(idx_names, inplace=True, drop=True)
```

**Comment by lgray** [comment]
So, found some strings as axes and it's a trivial addition. The only think left to check in order to completely establish the loop to and from spark is how systematics are handled in FAST.

**Comment by lgray** [comment]
very obsolete
