### ISSUE TITLE
[bug] plot1d crashes with overlay, binwnorm and empty histograms

### ISSUE THREAD

**Issue by AndreasAlbert** [scikit-hep/coffea#297]
**Describe the bug**
When using plot1d to make an overlay plot, a crash appears if the following conditions are met:
* one of the the overlay categories has exclusively been filled with empty arrays
* binwnorm is not None

**To Reproduce**
```python
import numpy as np
from coffea.hist import Hist, Bin, Cat, plot1d

# Example histogram
h = Hist(
    "test",
    Bin("x","x",2,0,2),
    Cat("cat","cat")
)

# cat1 is filled with some entries
h.fill(cat="cat1", x=np.array([0.5,1.5]))

# cat2 is filled with an empty array
h.fill(cat="cat2", x=np.array([]))

# Plot with bin width normalization
ax = plot1d(h, overlay="cat", binwnorm=1)

```

**Expected behavior**
I'd expect all non-empty categories to be plotted normally and the empty category to be plotted with all zero bin contents.

**Output**
```
/some/path/lib/python3.6/site-packages/coffea/hist/plot.py:44: RuntimeWarning: All sumw are zero!  Cannot compute meaningful error bars
  warnings.warn("All sumw are zero!  Cannot compute meaningful error bars", RuntimeWarning)
/some/path/lib/python3.6/site-packages/mplhep/_deprecate.py:56: DeprecationWarning: kwarg "densitymode" in function "histplot" is deprecated and may be removed in future versions: "unit"mode is not useful
  return func(*args, **kwargs)
/some/path/lib/python3.6/site-packages/mplhep/plot.py:226: RuntimeWarning: invalid value encountered in true_divide
  binnorms /= np.outer(np.diff(bins), per_hist_norm).T
Traceback (most recent call last):
  File "demo_nan_axis_lim.py", line 18, in <module>
    ax = plot1d(h, overlay="cat", binwnorm=1)
  File "/some/path/lib/python3.6/site-packages/coffea/hist/plot.py", line 264, in plot1d
    **kwargs)
  File "/some/path/lib/python3.6/site-packages/mplhep/_deprecate.py", line 56, in decorated_func
    return func(*args, **kwargs)
  File "/some/path/lib/python3.6/site-packages/mplhep/_deprecate.py", line 56, in decorated_func
    return func(*args, **kwargs)
  File "/some/path/lib/python3.6/site-packages/mplhep/plot.py", line 364, in histplot
    ax.set_ylim(ymin if np.min(h) < 0 else 0, np.max([ymax, 1.2 * np.max(h)]))
  File "/some/path/lib/python3.6/site-packages/matplotlib/axes/_base.py", line 3575, in set_ylim
    top = self._validate_converted_limits(top, self.convert_yunits)
  File "/some/path/lib/python3.6/site-packages/matplotlib/axes/_base.py", line 3101, in _validate_converted_limits
    raise ValueError("Axis limits cannot be NaN or Inf")
ValueError: Axis limits cannot be NaN or Inf


```

**Desktop (please complete the following information):**
coffea 0.6.38
mplhep 0.1.17

**Additional context**
I think this is caused by the way the bin normalizations are calculated in mplhep: @andrzejnovak, could you please take a look?

**Comment by andrzejnovak** [comment]
@AndreasAlbert  Thanks for spotting that. I reckon the expected behaviour is for empty arrays to just pass? akin to `plt.plot([], [], label="Empty")` ?

**Comment by AndreasAlbert** [comment]
Yes, exactly.
