### ISSUE TITLE
Workqueue executor CI tests are failing

### ISSUE THREAD

**Issue by nsmith-** [scikit-hep/coffea#345]
All daily CI has failed since Sep. 4th with:
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/tmp/tmpqhx8ji8c/lib/python3.8/site-packages/conda_pack/core.py", line 450, in pack
    env = CondaEnv.from_prefix(prefix,
  File "/tmp/tmpqhx8ji8c/lib/python3.8/site-packages/conda_pack/core.py", line 139, in from_prefix
    files = load_environment(prefix, **kwargs)
  File "/tmp/tmpqhx8ji8c/lib/python3.8/site-packages/conda_pack/core.py", line 781, in load_environment
    raise CondaPackException(_missing_files_error.format(packages))
conda_pack.core.CondaPackException: 
Files managed by conda were found to have been deleted/overwritten in the
following packages:

- python='3.8.5'

This is usually due to `pip` uninstalling or clobbering conda managed files,
resulting in an inconsistent environment. Please check your environment for
conda/pip conflicts using `conda list`, and fix the environment by ensuring
```
I disabled the test for python 3.8 for now (actually all but 3.7).

**Comment by nsmith-** [comment]
@zsurma let us know if you can debug this or if your time on the project has wrapped up.

**Comment by lgray** [comment]
To this end I've been working on getting coffea into conda properly. 
The error being emitted is from a pip/conda clash, so I suspect pulling that together may help.

**Comment by lgray** [comment]
@camicarballo @nsmith- following up on this now that we have coffea in conda. Even using the coffea from conda I'm seeing the same:
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/var/folders/5t/pyt3sm_52f9b17dgs46_nw0r0000gp/T/tmpimplqkub/lib/python3.8/site-packages/conda_pack/core.py", line 450, in pack
    env = CondaEnv.from_prefix(prefix,
  File "/var/folders/5t/pyt3sm_52f9b17dgs46_nw0r0000gp/T/tmpimplqkub/lib/python3.8/site-packages/conda_pack/core.py", line 139, in from_prefix
    files = load_environment(prefix, **kwargs)
  File "/var/folders/5t/pyt3sm_52f9b17dgs46_nw0r0000gp/T/tmpimplqkub/lib/python3.8/site-packages/conda_pack/core.py", line 781, in load_environment
    raise CondaPackException(_missing_files_error.format(packages))
conda_pack.core.CondaPackException: 
Files managed by conda were found to have been deleted/overwritten in the
following packages:

- python='3.8.5'

This is usually due to `pip` uninstalling or clobbering conda managed files,
resulting in an inconsistent environment. Please check your environment for
conda/pip conflicts using `conda list`, and fix the environment by ensuring
only one version of each package is installed (conda preferred).
Traceback (most recent call last):
  File "wq.py", line 95, in <module>
    create_conda_environment(environment_file, py_version)
  File "wq.py", line 86, in create_conda_environment
    subprocess.check_call(['/bin/bash', conda_recipe.name])
  File "/Users/lagray/miniconda3/envs/coffea/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/bin/bash', '/var/folders/5t/pyt3sm_52f9b17dgs46_nw0r0000gp/T/tmp_823_1e6']' returned non-zero exit status 1.
```

despite there being no pip being used at all in the install script any more!

Something's definitely off with python 3.8 and wq + coffea.

**Comment by lgray** [comment]
Has since been fixed.
