### ISSUE TITLE
XRootD with nanoaod.NanoEvents on Python 2/3

### ISSUE THREAD

**Issue by mondalspandan** [scikit-hep/coffea#351]
Hello, I was wondering how one could load files over xrootd using nanoaod.NanoEvents.from_file(). I see example codes where NanoEvents loads files over xrootd, but I could not make it work in either Python 2 or 3. The issues I run into are as follows:

**Python 2.7:**
- I can install XRootD with both conda and pip.
- I cannot install Coffea as it requires matplotlib >= 3 which in turn requires Python >= 3.5. I see the documentation says Coffea does work with Python 2 albeit in a deprecated mode, but I am not able to install it.

**Python 3.8:**
- I can install Coffea and read local files.
- If I try to load an XRootD file, the code fails with `ImportError: Install pyxrootd package with: conda install -c conda-forge xrootd`
- I am able to execute the `conda install` code to install xrootd normally, but trying to load files on Coffea over xrootd throws the same ImportError.
- I see xrootd itself is not supported for Python 3 yet.

Is there a recipe to make xrootd and Coffea work on the same Python version.

**Comment by lgray** [comment]
Do you have cvmfs available? If so you can use one of the lcg releases to get a python3 compatible version of xrootd. I'm not quite sure why it hasn't been updated in conda.

**Comment by nsmith-** [comment]
I'm sure conda has a working python3.7 xrootd, I have used it quite extensively. It may be that python3.8 has issues, but not sure. For my reference, can you point to where the statement that xrootd doesn't support python 3 is?

**Comment by nsmith-** [comment]
As for python2, we'll make an action item to declare python 2 unsupported by coffea. Indeed several of our dependencies are now python3-only.

**Comment by mondalspandan** [comment]
Hi Lindsey and Nick,

Using one of the lcg releases with Python 3 indeed solves the problem, thanks a lot!

> For my reference, can you point to where the statement that xrootd doesn't support python 3 is?

I was referring to [this repository](https://github.com/xrootd/xrootd-python). It seems it has not been maintained for quite some time, so it is possible that a new XRootD version for Python 3 is officially maintained elsewhere, given it indeed works with Python 3.

Thanks again!

**Comment by andrzejnovak** [comment]
That's not the one you get in conda afaik

**Comment by nsmith-** [comment]
Hi @mondalspandan I wonder if you can confirm the steps you took to create a python3.8 conda environment, showing the read error in coffea after installing xrootd?

**Comment by mondalspandan** [comment]
Hi Nick,

I do the following:

- Install conda 3.8 from the installer: `Anaconda3-2020.07-Linux-x86_64.sh`
- Install coffea using pip (I make sure conda is activated and it is the pip inside conda3/bin/): `pip install coffea`
- Read a file using coffea: `events = Events.from_file(fname)` where `fname` is an XRootD path.
- This fails and asks me to Install pyxrootd package [1].
- I install pyxrootd with `conda install -c conda-forge xrootd`. Installation works as expected.
- I try to read the file over XRootD again, it throws the same error.
- I try to run `conda install -c conda-forge xrootd` again, it says `# All requested packages already installed.`

Please let me know if you need further information.

[1]
```
Traceback (most recent call last): 
  File "/nfs/dust/cms/user/spmondal/anaconda3/lib/python3.8/site-packages/cachetools/cache.py", line 39, in __getitem__
    return self.__data[key] 
KeyError: 0

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/nfs/dust/cms/user/spmondal/anaconda3/lib/python3.8/site-packages/uproot/source/chunked.py", line 117, in data
    chunk = self.cache[chunkindex] 
  File "/nfs/dust/cms/user/spmondal/anaconda3/lib/python3.8/site-packages/uproot/cache.py", line 63, in __getitem__
    return self._cache[where] 
  File "/nfs/dust/cms/user/spmondal/anaconda3/lib/python3.8/site-packages/cachetools/lru.py", line 14, in __getitem__
    value = cache_getitem(self, key)
  File "/nfs/dust/cms/user/spmondal/anaconda3/lib/python3.8/site-packages/cachetools/cache.py", line 41, in __getitem__
    return self.__missing__(key)
  File "/nfs/dust/cms/user/spmondal/anaconda3/lib/python3.8/site-packages/cachetools/cache.py", line 68, in __missing__
    raise KeyError(key)
KeyError: 0

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/nfs/dust/cms/user/spmondal/anaconda3/lib/python3.8/site-packages/uproot/source/xrootd.py", line 28, in _open
    import pyxrootd.client 
ModuleNotFoundError: No module named 'pyxrootd'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "shapeCoffea.py", line 22, in <module>
    events = Events.from_file(fname)
  File "/afs/desy.de/user/s/spmondal/.local/lib/python3.8/site-packages/coffea/nanoaod/nanoevents.py", line 300, in from_file
    file = uproot.open(file)
  File "/nfs/dust/cms/user/spmondal/anaconda3/lib/python3.8/site-packages/uproot/rootio.py", line 57, in open
    return xrootd(path, xrootdsource=xrootdsource, **options) 
  File "/nfs/dust/cms/user/spmondal/anaconda3/lib/python3.8/site-packages/uproot/rootio.py", line 77, in xrootd
    return ROOTDirectory.read(openfcn(path), **options)
  File "/nfs/dust/cms/user/spmondal/anaconda3/lib/python3.8/site-packages/uproot/rootio.py", line 122, in read
    magic, fVersion = cursor.fields(source, ROOTDirectory._format1)
  File "/nfs/dust/cms/user/spmondal/anaconda3/lib/python3.8/site-packages/uproot/source/cursor.py", line 46, in fields
    return format.unpack(source.data(start, stop)) 
  File "/nfs/dust/cms/user/spmondal/anaconda3/lib/python3.8/site-packages/uproot/source/chunked.py", line 119, in data
    self._open()
  File "/nfs/dust/cms/user/spmondal/anaconda3/lib/python3.8/site-packages/uproot/source/xrootd.py", line 30, in _open
    raise ImportError("Install pyxrootd package with:\n    conda install -c conda-forge xrootd\n(or download from http://xrootd.org/dload.html and manually compile with cmake; setting PYTHONPATH and LD_LIBRARY_PATH appropriately).")
ImportError: Install pyxrootd package with:
    conda install -c conda-forge xrootd
(or download from http://xrootd.org/dload.html and manually compile with cmake; setting PYTHONPATH and LD_LIBRARY_PATH appropriately).
```

**Comment by nsmith-** [comment]
Hi @mondalspandan can you try to start a fresh conda environment and `conda install -c conda-forge xrootd` and then `pip install coffea` ? Just in case pip is clobbering conda.

**Comment by nsmith-** [comment]
For sure I know this conda-based installation procedure works: https://github.com/CoffeaTeam/coffea-farm/blob/master/docker/coffea-dask/Dockerfile#L14-L32

**Comment by lgray** [comment]
Stale it seems. Closing for now.
