### ISSUE TITLE
Order of operation dependent failure in either ak1 NanoEvents or awkward1

### ISSUE THREAD

**Issue by lgray** [scikit-hep/coffea#367]
Order dependence in valid math where one array is of fairly complex structure.
I can work around this for now, but obviously this is not desirable.
Here is a minimum repro when using coffea, I haven't dug into an ak1-only repro.

@nsmith- @jpivarski 

```python3
from coffea.nanoevents import NanoEventsFactory
fname = 'https://raw.githubusercontent.com/CoffeaTeam/coffea/master/tests/samples/nano_dy.root'
factory = NanoEventsFactory.from_file(fname)
events = factory.events()

gen_pt = awkward1.fill_none(events.Jet.matched_gen.pt, 0.)
jetPt = events.Jet.pt

print(-gen_pt + jetPt)  # produces correct answer
print(jetPt - gen_pt)  # fails with traceback as below
```

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/lagray/miniconda3/envs/coffea-work/lib/python3.7/site-packages/numpy/lib/mixins.py", line 21, in func
    return ufunc(self, other)
  File "/Users/lagray/miniconda3/envs/coffea-work/lib/python3.7/site-packages/awkward1/highlevel.py", line 1369, in __array_ufunc__
    return awkward1._connect._numpy.array_ufunc(ufunc, method, inputs, kwargs)
  File "/Users/lagray/miniconda3/envs/coffea-work/lib/python3.7/site-packages/awkward1/_connect/_numpy.py", line 174, in array_ufunc
    inputs, getfunction, behavior, allow_records=False
  File "/Users/lagray/miniconda3/envs/coffea-work/lib/python3.7/site-packages/awkward1/_util.py", line 996, in broadcast_and_apply
    out = apply(broadcast_pack(inputs, isscalar), 0)
  File "/Users/lagray/miniconda3/envs/coffea-work/lib/python3.7/site-packages/awkward1/_util.py", line 759, in apply
    outcontent = apply(nextinputs, depth + 1)
  File "/Users/lagray/miniconda3/envs/coffea-work/lib/python3.7/site-packages/awkward1/_util.py", line 847, in apply
    outcontent = apply(nextinputs, depth + 1)
  File "/Users/lagray/miniconda3/envs/coffea-work/lib/python3.7/site-packages/awkward1/_util.py", line 589, in apply
    depth,
  File "/Users/lagray/miniconda3/envs/coffea-work/lib/python3.7/site-packages/awkward1/_util.py", line 655, in apply
    nextinputs.append(x[mask].project(combo[str(i)]))
ValueError: no field of name 1
```

**Comment by lgray** [comment]
FYI in this repro

gen_pt is a:
```
<ListOffsetArray64>
    <offsets><Index64 i="[0 5 13 18 21 ... 176 179 180 186 188]" offset="0" length="41" at="0x7ff8e0d775a0"/></offsets>
    <content><UnionArray8_64>
        <tags><Index8 i="[0 0 0 1 1 ... 1 1 0 0 1]" offset="0" length="188" at="0x7ff8e0efb6a0"/></tags>
        <index><Index64 i="[0 1 2 0 0 ... 0 0 125 126 0]" offset="0" length="188" at="0x7ff8dec88400"/></index>
        <content index="0">
            <VirtualArray cache_key="ak.from_arrayset:0/a9490124-3648-11ea-89e9-f5b55c90beef/%2FEvents%3B1/0-40/GenJet_pt%2C%21load%2C%21content/virtual">
                <ArrayGenerator f="<function _form_to_layout at 0x11be3dcb0>" args="({
    "class": "NumpyArray",
    "itemsize": 4,
    "format": "f",
    "primitive": "float32",
    "parameters": {
        "__doc__": "pt"
    },
    "form_key": "GenJet_pt%2C%21load%2C%21content"
}, <coffea.nanoevents.mapping.UprootSourceMapping object at 0x10e49e790>, None, 'a9490124-3648-11ea-89e9-f5b55c90beef/%2FEvents%3B1/0-40/', '/', False, <ArrayCache mapping="<awkward1._util.MappingProxy object at 0x12f365..."/>, 'ak.from_arrayset:0', 127)">
                    <length>127</length>
                    <form>
                        {
                            "class": "NumpyArray",
                            "itemsize": 4,
                            "format": "f",
                            "primitive": "float32",
                            "parameters": {
                                "__doc__": "pt"
                            },
                            "form_key": "GenJet_pt%2C%21load%2C%21content"
                        }
                    </form>
                </ArrayGenerator>
                <ArrayCache mapping="<awkward1._util.MappingProxy object at 0x12f365..."/>
                <array><NumpyArray format="f" shape="127" data="87.5072 58.116 39.3962 32.6773 30.3838 ... 43.1404 44.6578 43.5262 10.7902 20.6055" at="0x7ff8e1c1e350">
                    <parameters>
                        <param key="__doc__">"pt"</param>
                    </parameters>
                </NumpyArray></array>
            </VirtualArray>
        </content>
        <content index="1">
            <NumpyArray format="d" shape="1" data="0" at="0x7ff8decdb600"/>
        </content>
    </UnionArray8_64></content>
</ListOffsetArray64>
```

and jetPt is a:
```
<ListOffsetArray64>
    <offsets><Index64 i="[0 5 13 18 21 ... 176 179 180 186 188]" offset="0" length="41" at="0x7ff8e0d775a0"/></offsets>
    <content><NumpyArray format="d" shape="188" data="8.59546 3.91821 4.92081 4.52783 3.27301 ... 2.0455 2.28864 -0.168709 2.15126 -0.401344" at="0x7ff8dfacb200"/></content>
</ListOffsetArray64>
```

**Comment by lgray** [comment]
Fixed in next awkward release.
