### ISSUE TITLE
File/entries error annotation printed twice

### ISSUE THREAD

**Issue by andrzejnovak** [scikit-hep/coffea#370]
@pfackeldey There is some duplication in the error message after your changes

<details>

```
The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/afs/desy.de/user/a/anovak/dust/miniconda3/lib/python3.7/concurrent/futures/process.py", line 239, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
  File "/afs/desy.de/user/a/anovak/coffea/coffea/processor/executor.py", line 129, in __call__
    out = self.function(*args, **kwargs)
  File "/afs/desy.de/user/a/anovak/coffea/coffea/processor/executor.py", line 877, in _work_function
    raise e
  File "/afs/desy.de/user/a/anovak/coffea/coffea/processor/executor.py", line 836, in _work_function
    raise Exception(f"Failed processing file: {item.filename} ({item.entrystart}-{item.entrystop})") from e
Exception: Failed processing file: root://xrootd-cms.infn.it///store/user/anovak/PFNano/106X_vA01/TTToSemiLeptonic_TuneCP5_13TeV-powheg-pythia8/RunIIFall17PFNanoAODv2-PU2017_12Apr2018_new_pmx_94X_mc2017_realistic_v14-v1/201118_010348/0000/nano106X_on_mini106X_2017_mc_NANO_10.root (0-259880)
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "runner.py", line 99, in <module>
    chunksize=args.chunk, maxchunks=args.max
  File "/afs/desy.de/user/a/anovak/coffea/coffea/processor/executor.py", line 1130, in run_uproot_job
    executor(chunks, closure, wrapped_out, **exe_args)
  File "/afs/desy.de/user/a/anovak/coffea/coffea/processor/executor.py", line 559, in futures_executor
    _futures_handler(futures, accumulator, status, unit, desc, add_fn, tailtimeout)
  File "/afs/desy.de/user/a/anovak/coffea/coffea/processor/executor.py", line 187, in _futures_handler
    add_fn(output, finished.pop().result())
  File "/afs/desy.de/user/a/anovak/dust/miniconda3/lib/python3.7/concurrent/futures/_base.py", line 428, in result
    return self.__get_result()
  File "/afs/desy.de/user/a/anovak/dust/miniconda3/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
Exception: Failed processing file: root://xrootd-cms.infn.it///store/user/anovak/PFNano/106X_vA01/TTToSemiLeptonic_TuneCP5_13TeV-powheg-pythia8/RunIIFall17PFNanoAODv2-PU2017_12Apr2018_new_pmx_94X_mc2017_realistic_v14-v1/201118_010348/0000/nano106X_on_mini106X_2017_mc_NANO_10.root (0-259880)
```

</details>

**Comment by lgray** [comment]
@pfackeldey can you please take a look at this? (after the break, of course) :-)

**Comment by pfackeldey** [comment]
Hi @andrzejnovak @lgray ,
sorry for getting so late to this.

The related PR is here: https://github.com/CoffeaTeam/coffea/pull/360
The intention of my PR was to use directly pythons exceptions chain syntax, since the old implementation assumed that the constructor of *every* exception is called in the same way. I thought this was not the safest way and is directly fixed through exception chaining.
I did not notice so far the duplication of error messages, probably because we are working with Dask which usually produces so much output on an error that the second `Failed processing file: ...` got lost in the output (?).
Can you confirm that this happens with every type of executor?
Personally I have no strong preference, if you want please revert the related commit. 

Best, Peter
