### ISSUE TITLE
A bug was found in coffea.XYZ

### ISSUE THREAD

**Issue by Keane-Tan** [scikit-hep/coffea#377]
**Describe the bug**
Coffea could not handle the "TriggerNames" branch in the ntuples made with an older TreeMaker.
The following line in dataframe.py seems be the source of the problem? :
array = [self._tree[key].array(**self._branchargs)]

**To Reproduce**
1. Download the code in the this link (https://github.com/Keane-Tan/Test/blob/new/analyze_simplified.py) and run
`python analyze_simplified.py`

**Expected behavior**
If you run the code in the link on cmslpc (after setting up coffea and everything), you may get the following error:

AttributeError: 'NoneType' object has no attribute 'update'

If you comment out line 25: triggerNames = df['TriggerNames']. 

The code will run without any problem. The code will also run if you change the chunksize to 5000 instead of 10000 without commenting out line 25.

**Desktop (please complete the following information):**
 - cmslpc-sl7

**Comment by kpedro88** [comment]
Reading `vector<string>` should work in uproot: https://github.com/scikit-hep/uproot3/issues/32
So maybe it's a problem with the `LazyDataFrame`...

**Comment by nsmith-** [comment]
Looks like, surprisingly, an xrootd issue:
```python
>>> import uproot4
>>> f = uproot4.open("root://cmseos.fnal.gov//store/user/lpcsusyhad/SusyRA2Analysis2015/Run2ProductionV17/Autumn18.QCD_Pt_1000to1400_TuneCP5_13TeV_pythia8_0_RA2AnalysisTree.root")
>>> f["TreeMaker2/PreSelection"]["TriggerNames"].array(entry_stop=1000)
<Array [...] type='1000 * var * string'>
>>> f["TreeMaker2/PreSelection"]["TriggerNames"].array(entry_stop=10000)
Traceback (most recent call last):
  File "/uscms_data/d3/ncsmith/miniconda3/envs/daskfarm/lib/python3.7/site-packages/XRootD/client/utils.py", line 34, in __call__
    self.response = self.responsetype(response)
  File "/uscms_data/d3/ncsmith/miniconda3/envs/daskfarm/lib/python3.7/site-packages/XRootD/client/responses.py", line 202, in __init__
    info.update({'chunks': [ChunkInfo(c) for c in info['chunks']]})
AttributeError: 'NoneType' object has no attribute 'update'
```

If I open the file using the fuse mount:
```python
>>> f = uproot4.open("/eos/uscms/store/user/lpcsusyhad/SusyRA2Analysis2015/Run2ProductionV17/Autumn18.QCD_Pt_1000to1400_TuneCP5_13TeV_pythia8_0_RA2AnalysisTree.root")
>>> f["TreeMaker2/PreSelection"]["TriggerNames"].array(entry_stop=10000)
<Array [...] type='10000 * var * string'>
>>> a = f["TreeMaker2/PreSelection"]["TriggerNames"].array(entry_stop=10000)
>>> a[0]
<Array [...] type='148 * string'>
>>> a[0][1]
'HLT_AK8DiPFJet280_200_TrimMass30_v'
```
My guess is that the arrangement of baskets in this file causes some unusual vector read to be called by uproot that xrootd then chokes on. If I use the xrootd source that doesn't use vector reads, then it works ok:
```python
>>> uproot4.open.defaults["xrootd_handler"] = uproot4.source.xrootd.MultithreadedXRootDSource
>>> f = uproot4.open("root://cmseos.fnal.gov//store/user/lpcsusyhad/SusyRA2Analysis2015/Run2ProductionV17/Autumn18.QCD_Pt_1000to1400_TuneCP5_13TeV_pythia8_0_RA2AnalysisTree.root")
>>> a = f["TreeMaker2/PreSelection"]["TriggerNames"].array(entry_stop=10000)
>>> a[0][1]
'HLT_AK8DiPFJet280_200_TrimMass30_v'
```
This is similar but probably not the same as https://github.com/scikit-hep/uproot4/issues/122 FYI @jpivarski 

For your purpose, it should be enough to add the lines:
```python
import uproot4
uproot4.open.defaults["xrootd_handler"] = uproot4.source.xrootd.MultithreadedXRootDSource
```
at the top of your file to work around this issue.

**Comment by nsmith-** [comment]
Unrelated to the original issue, I did notice a loop over events in your example file, which is generally not very performant. You can replace the lines
```python
                tPassedList = []
                for evt in triggerPass:
                    tPassed = [tp for tp in range(len(evt)) if evt[tp] == 1]
                    tPassedList.append(tPassed)
                tPassedList = ak.Array(tPassedList)
```
with `tPassedList = ak.from_awkward0(triggerPass.localindex[triggerPass==1])`

**Comment by jpivarski** [comment]
To be sure that this isn't missed, "local index" exists in Awkward 1 now, too: [ak.local_index](https://awkward-array.readthedocs.io/en/latest/_auto/ak.local_index.html).

```python
ak.local_index(ak.from_awkward0(triggerPass))[triggerPass == 1]
```

**Comment by nsmith-** [comment]
True, that also works. In fact, the awkward1 version of triggerNames is much more useful, however the coffea dataframe is, for compatiblity reasons, turning all the output into awkward0 arrays so we lose this.
For example, if you reach under the hood and grab the ak1 triggerNames, the following code can be used to directly evaluate if a given trigger path fired per event in a vectorized fashion:
```python
triggerNames = df._tree["TriggerNames"].array(**df._branchargs)
passes_this = ak.any(triggerPass[triggerNames == "HLT_AK8DiPFJet280_200_TrimMass30_v"] == 1, axis=1)
```
which produces a boolean array (false if the trigger name does not exist)

That said, the majority of the runtime for this example is reading and decompressing the `triggerNames` branch. If the indices are known to be constant for the whole dataset, one could vastly improve the runtime by never reading `triggerNames`

**Comment by kpedro88** [comment]
@nsmith- in newer ntuple versions, TriggerNames is no longer a branch, but specified as metadata for TriggerPass (ala nanoAOD).

**Comment by lgray** [comment]
Did this issue reach any sort of resolution?

**Comment by nsmith-** [comment]
From https://github.com/CoffeaTeam/coffea/issues/377#issuecomment-740233257 I claim the bug is actually in the vector-read xrootd source in uproot. @jpivarski do you agree?

**Comment by nsmith-** [comment]
FYI https://github.com/scikit-hep/uproot4/pull/243 may potentially solve this issue

**Comment by nsmith-** [comment]
Closing due to inactivity. Reopen if this is still an issue
