### ISSUE TITLE
Problem with coffea 0.6.46: ModuleNotFoundError: No module named 'awkward.array'

### ISSUE THREAD

**Issue by fiemmi** [scikit-hep/coffea#379]
**Describe the bug**
Dear all, I installed coffea by doing `pip install coffea --use-feature=2020-resolver`. Everything went smoothly and no errors were prompted. Still, it seems something is happening with the dependencies, since a line of code as simple as `from coffea import hist` gives me the following error:

```
Traceback (most recent call last):
  File "analysis.py", line 1, in <module>
    from coffea import hist
  File "/home/ubuntu/anaconda3/lib/python3.8/site-packages/coffea/__init__.py", line 39, in <module>
    from . import (
  File "/home/ubuntu/anaconda3/lib/python3.8/site-packages/coffea/hist/__init__.py", line 13, in <module>
    from .hist_tools import (
  File "/home/ubuntu/anaconda3/lib/python3.8/site-packages/coffea/hist/hist_tools.py", line 4, in <module>
    from coffea.processor.accumulator import AccumulatorABC
  File "/home/ubuntu/anaconda3/lib/python3.8/site-packages/coffea/processor/__init__.py", line 11, in <module>
    from .executor import (
  File "/home/ubuntu/anaconda3/lib/python3.8/site-packages/coffea/processor/executor.py", line 31, in <module>
    from ..nanoaod import NanoEvents
  File "/home/ubuntu/anaconda3/lib/python3.8/site-packages/coffea/nanoaod/__init__.py", line 13, in <module>
    from .nanoevents import NanoCollection, NanoEvents
  File "/home/ubuntu/anaconda3/lib/python3.8/site-packages/coffea/nanoaod/nanoevents.py", line 4, in <module>
    from .methods import collection_methods
  File "/home/ubuntu/anaconda3/lib/python3.8/site-packages/coffea/nanoaod/methods/__init__.py", line 7, in <module>
    from .common import METVector, LorentzVector, Candidate
  File "/home/ubuntu/anaconda3/lib/python3.8/site-packages/coffea/nanoaod/methods/common.py", line 3, in <module>
    from uproot_methods.classes.TLorentzVector import PtEtaPhiMassArrayMethods
  File "/home/ubuntu/anaconda3/lib/python3.8/site-packages/uproot_methods/__init__.py", line 5, in <module>
    from uproot_methods.classes.TVector2 import TVector2, TVector2Array
  File "/home/ubuntu/anaconda3/lib/python3.8/site-packages/uproot_methods/classes/TVector2.py", line 8, in <module>
    import awkward.array.jagged
ModuleNotFoundError: No module named 'awkward.array'
```
To me, it seems the problem is related to uproot-methods and awkward. uproot-methods version is 0.8.0; awkward version is 1.0.0. No idea how to solve it. Is it a bug, or I am missing something?

**To Reproduce**
I basically did nothing more than
1. Installing Anaconda3-2020.11
2. Installing coffea
3. Running  a macro with first line `from coffea import hist`, which raises the error

**Desktop (please complete the following information):**
 - OS: VM running Ubuntu 16.04.6 LTS (GNU/Linux 4.4.0-154-generic x86_64)
 - Python version: 3.8
- pip version: 20.2.4

Have no idea about how to solve this, any help would be very appreciated. Thanks!

Cheers,
Fabio.

**Comment by nsmith-** [comment]
This is a side-effect of the awkward-array renaming that recently finished. I had prepared a patch in https://github.com/CoffeaTeam/coffea/pull/378 but did not create a new release. Doing so now. When coffea 0.6.47 is available it should not have this issue

**Comment by fiemmi** [comment]
Dear @nsmith-,

thanks a lot for the quick reply. It's good to hear that the issue is not related to any local problem on my side. Is there an estimated timescale for the new coffea release?

Thanks a lot for your help, cheers,
F.

**Comment by nsmith-** [comment]
Looks like it's out on pypi already: https://pypi.org/project/coffea/ (if you used `pip install coffea`)
Conda should follow shortly (if you used `conda install coffea`)

**Comment by fiemmi** [comment]
Hi @nsmith-,

as a followup, I confirm that installing coffea 0.6.47 solves the issue. Thanks a lot!
