### ISSUE TITLE
 ModuleNotFoundError in coffea.0.7.2

### ISSUE THREAD

**Issue by kakwok** [scikit-hep/coffea#485]
**Describe the bug**
Fail to import certain module after upgrading to version 0.7.2

**To Reproduce**
```
>>> coffea.__version__
'0.7.2'
>>> from coffea.nanoevents.methods import vector
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/uscms/home/kkwok/work/LLP/CMSSW_10_6_20/src/llp_analyzer/coffeaenv/lib/python3.6/site-packages/coffea/nanoevents/__init__.py", line 4, in <module>
    from coffea.nanoevents.factory import NanoEventsFactory
  File "/uscms/home/kkwok/work/LLP/CMSSW_10_6_20/src/llp_analyzer/coffeaenv/lib/python3.6/site-packages/coffea/nanoevents/factory.py", line 11, in <module>
    from coffea.nanoevents.mapping import (
  File "/uscms/home/kkwok/work/LLP/CMSSW_10_6_20/src/llp_analyzer/coffeaenv/lib/python3.6/site-packages/coffea/nanoevents/mapping/__init__.py", line 2, in <module>
    from .parquet import TrivialParquetOpener, ParquetSourceMapping
  File "/uscms/home/kkwok/work/LLP/CMSSW_10_6_20/src/llp_analyzer/coffeaenv/lib/python3.6/site-packages/coffea/nanoevents/mapping/parquet.py", line 9, in <module>
    import pyarrow.dataset as ds
ModuleNotFoundError: No module named 'pyarrow.dataset'
```

**Desktop (please complete the following information):**
 sl7 on LPC cluster

**Comment by nsmith-** [comment]
Likely the issue is we have an improper version requirement for pyarrow in https://github.com/CoffeaTeam/coffea/blob/8c58807e199a7694bf15e3803dbaf706d34bbfa0/setup.py#L62
A workaround is to just update pyarrow, e.g. with `pip install --upgrade pyarrow`
@lgray @JayjeetAtGithub do you know what minimum pyarrow version do we need for `pyarrow.dataset` to be available?

**Comment by nsmith-** [comment]
Actually I think some LCG releases distribute pyarrow < 1.0 and then this is the usual issue with LCG putting its python path in front of local virtualenv packages. There is a recipe in https://coffeateam.github.io/coffea/installation.html#creating-a-cvmfs-based-portable-virtual-environment using `LOCALPATH` to put the virtualenv back in front of `$PYTHONPATH` so the LCG release doesn't get in the way.

**Comment by kakwok** [comment]
Yes! Setting the `LOCALTPATH` works! Thanks!

**Comment by nsmith-** [comment]
Glad to hear! We should probably clarify our LCG-based installation since this is a familiar issue

**Comment by kakwok** [comment]
If others are also using the `cvmfs-based` script + jupyter workflow, it's better to add the `$PWD` in the script to make sure jupyter will pickup the same local path

```
LOCALPATH=$PWD/$NAME$(python -c 'import sys; print(f"/lib/python{sys.version_info.major}.{sys.version_info.minor}/site-packages")')
```
