### ISSUE TITLE
A bug was found in resource_mode and resource_monitoring for executor arguments for the work_queue executor

### ISSUE THREAD

**Issue by David-Simonetti-ND** [scikit-hep/coffea#628]
**Describe the bug**
Adding the resources_mode or resource_monitor arguments into the executor_args dictionary causes the program to crash. When printing out the debug/resource information for a given coffea task, attempting to access self.resources_measured.cores returns an AttributeError: 'NoneType' object has no attribute 'cores'

**To Reproduce**
Add 'resources_mode' : 'auto'  or 'resource_monitor' : True to the executor arg dictionary.

**Expected behavior**
Not crashing

**Output**
Run the wq-coffea example
------------------------------------------------
Example Coffea Analysis with Work Queue Executor
------------------------------------------------
Master Name: -N coffea-wq-dsimone2
Environment: coffea-env.tar.gz
Wrapper Path: /afs/crc.nd.edu/user/d/dsimone2/miniconda3/envs/coffea-env/bin/python_package_run
------------------------------------------------
Listening for work queue workers on port 9123...
warning: this work queue manager is visible to the public.
warning: you should set a password with the --password option.
warning: using plain-text when communicating with workers.
warning: use encryption with a key and cert when creating the manager.
submitted preprocessing task 1                                                                                                                            
submitted preprocessing task 2                                                                                                                            
Preprocessing   0%|                                                                                | 0/2 [00:00<?, ?file/s]                               2021/12/13 04:28:19.48 work_queue_python[2173] notice: Cannot open resources summary file: .//wq-2173-task-1.summary : No such file or directory
preprocessing task id 1 item pre_1 with 1 events completed on d12chas070.crc.nd.edu. return code 127                                                      
    allocated cores: 2.0, memory: 2000.0 MB, disk: 2000.0 MB, gpus: 0.0                                                                                   
Preprocessing   0%|                                                                                | 0/2 [00:05<?, ?file/s]                               Traceback (most recent call last):
  File "/afs/crc.nd.edu/user/d/dsimone2/Documentation/wq6.py", line 171, in <module>
    output = processor.run_uproot_job(
  File "/afs/crc.nd.edu/user/d/dsimone2/miniconda3/envs/coffea-env/lib/python3.9/site-packages/coffea/processor/__init__.py", line 104, in _run_x_job
    return run(
  File "/afs/crc.nd.edu/user/d/dsimone2/miniconda3/envs/coffea-env/lib/python3.9/site-packages/coffea/processor/executor.py", line 1267, in __call__
    self._preprocess_fileset(fileset)
  File "/afs/crc.nd.edu/user/d/dsimone2/miniconda3/envs/coffea-env/lib/python3.9/site-packages/coffea/processor/executor.py", line 1063, in _preprocess_fileset
    out = pre_executor(to_get, closure, out)
  File "/afs/crc.nd.edu/user/d/dsimone2/miniconda3/envs/coffea-env/lib/python3.9/site-packages/coffea/processor/executor.py", line 457, in __call__
    return work_queue_main(
  File "/afs/crc.nd.edu/user/d/dsimone2/miniconda3/envs/coffea-env/lib/python3.9/site-packages/coffea/processor/work_queue_tools.py", line 547, in work_queue_main
    return _work_queue_preprocessing(
  File "/afs/crc.nd.edu/user/d/dsimone2/miniconda3/envs/coffea-env/lib/python3.9/site-packages/coffea/processor/work_queue_tools.py", line 754, in _work_queue_preprocessing
    success = task.report(
  File "/afs/crc.nd.edu/user/d/dsimone2/miniconda3/envs/coffea-env/lib/python3.9/site-packages/coffea/processor/work_queue_tools.py", line 253, in report
    self.resources_measured.cores,
AttributeError: 'NoneType' object has no attribute 'cores'

**Desktop (please complete the following information):**
Linux Red Hat 4.8.5-39

**Additional context**

**Comment by nsmith-** [comment]
@btovar FYI

**Comment by btovar** [comment]
On it...

**Comment by btovar** [comment]
Not a coffea bug. (@nsmith-  could you close this issue?)
