### ISSUE TITLE
XRootD issues with LCG nightly?

### ISSUE THREAD

**Issue by patrickbryant** [scikit-hep/coffea#677]
I've been using 
```
source /cvmfs/sft.cern.ch/lcg/nightlies/dev4/Mon/coffea/0.7.13/x86_64-centos7-gcc10-opt/coffea-env.sh
```
to play with coffea and have run into an issue when trying to access files with XRootD:
```
Traceback (most recent call last):
  File "/cvmfs/sft-nightlies.cern.ch/lcg/nightlies/dev4/Mon/Python/3.9.12/x86_64-centos7-gcc10-opt/lib/python3.9/concurrent/futures/process.py", line 243, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
  File "/cvmfs/sft-nightlies.cern.ch/lcg/nightlies/dev4/Mon/coffea/0.7.13/x86_64-centos7-gcc10-opt/lib/python3.9/site-packages/coffea/processor/executor.py", line 990, in automatic_retries
    raise e
  File "/cvmfs/sft-nightlies.cern.ch/lcg/nightlies/dev4/Mon/coffea/0.7.13/x86_64-centos7-gcc10-opt/lib/python3.9/site-packages/coffea/processor/executor.py", line 978, in automatic_retries
    return func(*args, **kwargs)
  File "/cvmfs/sft-nightlies.cern.ch/lcg/nightlies/dev4/Mon/coffea/0.7.13/x86_64-centos7-gcc10-opt/lib/python3.9/site-packages/coffea/processor/executor.py", line 1041, in metadata_fetcher
    file = uproot.open(item.filename, timeout=xrootdtimeout)
  File "/cvmfs/sft-nightlies.cern.ch/lcg/nightlies/dev4/Mon/uproot/4.2.0/x86_64-centos7-gcc10-opt/lib/python3.9/site-packages/uproot/reading.py", line 141, in open
    file = ReadOnlyFile(
  File "/cvmfs/sft-nightlies.cern.ch/lcg/nightlies/dev4/Mon/uproot/4.2.0/x86_64-centos7-gcc10-opt/lib/python3.9/site-packages/uproot/reading.py", line 580, in __init__
    self._source = Source(
  File "/cvmfs/sft-nightlies.cern.ch/lcg/nightlies/dev4/Mon/uproot/4.2.0/x86_64-centos7-gcc10-opt/lib/python3.9/site-packages/uproot/source/xrootd.py", line 453, in __init__
    self._open()
  File "/cvmfs/sft-nightlies.cern.ch/lcg/nightlies/dev4/Mon/uproot/4.2.0/x86_64-centos7-gcc10-opt/lib/python3.9/site-packages/uproot/source/xrootd.py", line 457, in _open
    [
  File "/cvmfs/sft-nightlies.cern.ch/lcg/nightlies/dev4/Mon/uproot/4.2.0/x86_64-centos7-gcc10-opt/lib/python3.9/site-packages/uproot/source/xrootd.py", line 458, in <listcomp>
    XRootDResource(self._file_path, self._timeout)
  File "/cvmfs/sft-nightlies.cern.ch/lcg/nightlies/dev4/Mon/uproot/4.2.0/x86_64-centos7-gcc10-opt/lib/python3.9/site-packages/uproot/source/xrootd.py", line 83, in __init__
    self._open()
  File "/cvmfs/sft-nightlies.cern.ch/lcg/nightlies/dev4/Mon/uproot/4.2.0/x86_64-centos7-gcc10-opt/lib/python3.9/site-packages/uproot/source/xrootd.py", line 86, in _open
    XRootD_client = uproot.extras.XRootD_client()
  File "/cvmfs/sft-nightlies.cern.ch/lcg/nightlies/dev4/Mon/uproot/4.2.0/x86_64-centos7-gcc10-opt/lib/python3.9/site-packages/uproot/extras.py", line 74, in XRootD_client
    import XRootD.client
  File "/cvmfs/sft-nightlies.cern.ch/lcg/nightlies/dev4/Mon/xrootd/5.4.2/x86_64-centos7-gcc10-opt/lib/python3.9/site-packages/XRootD/client/__init__.py", line 3, in <module>
    from .glob_funcs import glob, iglob
  File "/cvmfs/sft-nightlies.cern.ch/lcg/nightlies/dev4/Mon/xrootd/5.4.2/x86_64-centos7-gcc10-opt/lib/python3.9/site-packages/XRootD/client/glob_funcs.py", line 26, in <module>
    from XRootD.client.filesystem import FileSystem
  File "/cvmfs/sft-nightlies.cern.ch/lcg/nightlies/dev4/Mon/xrootd/5.4.2/x86_64-centos7-gcc10-opt/lib/python3.9/site-packages/XRootD/client/filesystem.py", line 26, in <module>
    from pyxrootd import client
ImportError: libXrdCl.so.3: cannot open shared object file: No such file or directory
```

Any ideas?

**Comment by patrickbryant** [comment]
The XRootD dependency was missing. It has been added: https://gitlab.cern.ch/sft/lcgcmake/-/merge_requests/1293

**Comment by lgray** [comment]
Thanks for taking care of this - we largely tend to our containers. Nice to see it in lcg! Thanks!
