### ISSUE TITLE
Cannot import BTagScaleFactor coffea.0.7.13

### ISSUE THREAD

**Issue by patrickbryant** [scikit-hep/coffea#679]
```
from coffea.btag_tools import BTagScaleFactor
```
produces
```
Python 3.9.12 (main, May 11 2022, 02:50:52) 
[GCC 10.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import coffea
>>> coffea.__version__
'0.7.13'
>>> from coffea.btag_tools import BTagScaleFactor
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/cvmfs/sft-nightlies.cern.ch/lcg/nightlies/dev4/Mon/coffea/0.7.13/x86_64-centos7-gcc10-opt/lib/python3.9/site-packages/coffea/btag_tools/__init__.py", line 6, in <module>
    from .btagscalefactor import BTagScaleFactor
  File "/cvmfs/sft-nightlies.cern.ch/lcg/nightlies/dev4/Mon/coffea/0.7.13/x86_64-centos7-gcc10-opt/lib/python3.9/site-packages/coffea/btag_tools/btagscalefactor.py", line 3, in <module>
    from coffea.lookup_tools.dense_mapped_lookup import dense_mapped_lookup
  File "/cvmfs/sft-nightlies.cern.ch/lcg/nightlies/dev4/Mon/coffea/0.7.13/x86_64-centos7-gcc10-opt/lib/python3.9/site-packages/coffea/lookup_tools/__init__.py", line 7, in <module>
    from .extractor import extractor
  File "/cvmfs/sft-nightlies.cern.ch/lcg/nightlies/dev4/Mon/coffea/0.7.13/x86_64-centos7-gcc10-opt/lib/python3.9/site-packages/coffea/lookup_tools/extractor.py", line 8, in <module>
    from coffea.lookup_tools.json_converters import (
  File "/cvmfs/sft-nightlies.cern.ch/lcg/nightlies/dev4/Mon/coffea/0.7.13/x86_64-centos7-gcc10-opt/lib/python3.9/site-packages/coffea/lookup_tools/json_converters.py", line 2, in <module>
    import correctionlib
  File "/cvmfs/sft-nightlies.cern.ch/lcg/nightlies/dev4/Mon/correctionlib/2.1.0/x86_64-centos7-gcc10-opt/lib/python3.9/site-packages/correctionlib/__init__.py", line 17, in <module>
    from .highlevel import Correction, CorrectionSet
  File "/cvmfs/sft-nightlies.cern.ch/lcg/nightlies/dev4/Mon/correctionlib/2.1.0/x86_64-centos7-gcc10-opt/lib/python3.9/site-packages/correctionlib/highlevel.py", line 10, in <module>
    import correctionlib._core
ImportError: libcorrectionlib.so: cannot open shared object file: No such file or directory
```

I am using the LCG nightly on the cmslpc:
```
source /cvmfs/sft.cern.ch/lcg/nightlies/dev4/Mon/coffea/0.7.13/x86_64-centos7-gcc10-opt/coffea-env.sh 
```

**Comment by patrickbryant** [comment]
I created an LCG jira subtask: https://sft.its.cern.ch/jira/browse/SPI-2165

**Comment by patrickbryant** [comment]
Ok the issue was that the LCG env setup script does not play well with zsh and you must switch to bash before using it.
