### ISSUE TITLE
Nearest function not working for all cases on coffea 0.7.20

### ISSUE THREAD

**Issue by cmantill** [scikit-hep/coffea#750]
**Describe the bug**
Code that uses the `nearest` function with nanoEvents objects seems to have broken with the latest image.
Code worked with earlier version of coffea ([0.7.12](https://github.com/CoffeaTeam/coffea/releases/tag/v0.7.12)) 

**To Reproduce**
1. Here is a code snippet:
```
from coffea.nanoevents import NanoEventsFactory
import awkward as ak

import warnings
import numpy as np
warnings.filterwarnings("ignore", message="Found duplicate branch ")
warnings.filterwarnings("ignore", category=DeprecationWarning)
warnings.filterwarnings("ignore", message="Missing cross-reference index ")
warnings.filterwarnings("ignore", message="divide by zero encountered in log")
np.seterr(invalid="ignore")

events = NanoEventsFactory.from_root("root://cmsxrootd.fnal.gov//store/user/lpcpfnano/cmantill/v2_2/2017/HWW/GluGluHToWW_Pt-200ToInf_M-125_TuneCP5_MINLO_13TeV-powheg-pythia8/GluGluHToWW_Pt-200ToInf_M-125\
/220629_181652/0000/nano_mc2017_1-1.root").events()

higgs = events.GenPart[abs(events.GenPart.pdgId)==25 & events.GenPart.hasFlags(['fromHardProcess', 'isLastCopy'])]
higgs = higgs[ ak.all(abs(higgs.children.pdgId) == 24, axis=2) ]
jet = ak.firsts(events.FatJet)

# this works                                                                                                                                                                                                
print(events.FatJet.nearest(higgs))

# but this doesn't                                                                                                                                                                                          
print(jet.nearest(higgs))
print(jet.nearest(ak.firsts(higgs)))
```
3. run on `local multiprocessing`
4. See error:
```
Traceback (most recent call last):
  File "test.py", line 19, in <module>
    print(jet.nearest(ak.firsts(higgs)))
  File "/opt/conda/lib/python3.8/site-packages/coffea/nanoevents/methods/vector.py", line 730, in nearest
    mval, (a, b) = self.metric_table(other, axis, metric, return_combinations=True)
  File "/opt/conda/lib/python3.8/site-packages/coffea/nanoevents/methods/vector.py", line 694, in metric_table
    awkward.cartesian([self, other], axis=axis, nested=True)
  File "/opt/conda/lib/python3.8/site-packages/awkward/operations/structure.py", line 3562, in cartesian
    out = ak._util.broadcast_and_apply(
  File "/opt/conda/lib/python3.8/site-packages/awkward/_util.py", line 1172, in broadcast_and_apply
    out = apply(broadcast_pack(inputs, isscalar), 0, user)
  File "/opt/conda/lib/python3.8/site-packages/awkward/_util.py", line 925, in apply
    outcontent = apply(nextinputs, depth + 1, user)
  File "/opt/conda/lib/python3.8/site-packages/awkward/_util.py", line 881, in apply
    outcontent = apply(nextinputs, depth, user)
  File "/opt/conda/lib/python3.8/site-packages/awkward/_util.py", line 925, in apply
    outcontent = apply(nextinputs, depth + 1, user)
  File "/opt/conda/lib/python3.8/site-packages/awkward/_util.py", line 881, in apply
    outcontent = apply(nextinputs, depth, user)
  File "/opt/conda/lib/python3.8/site-packages/awkward/_util.py", line 1077, in apply
    raise ValueError(
ValueError: cannot broadcast records because keys don't match:
    DDX_jetNSecondaryVertices, DDX_jetNTracks, DDX_tau1_flightDistance2dSig, DDX_tau1_trackEtaRel_0, DDX_tau1_trackEtaRel_1, DDX_tau1_trackEtaRel_2, DDX_tau1_trackSip3dSig_0, DDX_tau1_trackSip3dSig_1, DDX_tau1_vertexDeltaR, DDX_tau1_vertexEnergyRatio, DDX_tau1_vertexMass, DDX_tau2_flightDistance2dSig, DDX_tau2_trackEtaRel_0, DDX_tau2_trackEtaRel_1, DDX_tau2_trackEtaRel_3, DDX_tau2_trackSip3dSig_0, DDX_tau2_trackSip3dSig_1, DDX_tau2_vertexEnergyRatio, DDX_tau2_vertexMass, DDX_trackSip2dSigAboveBottom_0, DDX_trackSip2dSigAboveBottom_1, DDX_trackSip2dSigAboveCharm, DDX_trackSip3dSig_0, DDX_trackSip3dSig_1, DDX_trackSip3dSig_2, DDX_trackSip3dSig_3, DDX_z_ratio, Proba, area, btagCSVV2, btagDDBvLV2, btagDDCvBV2, btagDDCvLV2, btagDeepB, btagDeepB_b, btagDeepB_bb, btagDeepL, btagHbb, deepTagMD_H4qvsQCD, deepTagMD_HbbvsQCD, deepTagMD_TvsQCD, deepTagMD_WvsQCD, deepTagMD_ZHbbvsQCD, deepTagMD_ZHccvsQCD, deepTagMD_ZbbvsQCD, deepTagMD_ZvsQCD, deepTagMD_bbvsLight, deepTagMD_ccvsLight, deepTag_H, deepTag_QCD, deepTag_QCDothers, deepTag_TvsQCD, deepTag_WvsQCD, deepTag_ZvsQCD, electronIdx3SJ, eta, genJetAK8Idx, genJetAK8IdxG, hadronFlavour, jetId, lsf3, mass, msoftdrop, muonIdx3SJ, n2b1, n3b1, nBHadrons, nCHadrons, nConstituents, pFCandsIdxG, particleNetMD_QCD, particleNetMD_Xbb, particleNetMD_Xcc, particleNetMD_Xqq, particleNet_H4qvsQCD, particleNet_HbbvsQCD, particleNet_HccvsQCD, particleNet_QCD, particleNet_TvsQCD, particleNet_WvsQCD, particleNet_ZvsQCD, particleNet_mass, phi, pt, rawFactor, subJetIdx1, subJetIdx1G, subJetIdx2, subJetIdx2G, subJetIdxG, tau1, tau2, tau3, tau4
    childrenIdxG, distinctChildrenIdxG, distinctParentIdxG, eta, genPartIdxMother, genPartIdxMotherG, mass, pdgId, phi, pt, status, statusFlags
```

**Expected behavior**
I expected nearest to be able to return the GenParticle nearest to my candidate jet.

**Comment by lgray** [comment]
What version of python are you using? Or you're otherwise using the latest singularity image?

**Comment by cmantill** [comment]
I am using the latest singularity image with python version `3.8.13`.

**Comment by lgray** [comment]
Using the latest singularity image: I'm not able to get the same error from your reproducer but it's a bit more informative:
```
[[GenParticle], [GenParticle, GenParticle], ... [], [GenParticle, GenParticle]]
Traceback (most recent call last):
  File "cristina_test.py", line 18, in <module>
    print(jet.nearest(higgs))
  File "/opt/conda/lib/python3.8/site-packages/coffea/nanoevents/methods/vector.py", line 735, in nearest
    out = awkward.firsts(b[mmin], axis=axis + 1)
  File "/opt/conda/lib/python3.8/site-packages/awkward/highlevel.py", line 991, in __getitem__
    tmp = ak._util.wrap(self.layout[where], self._behavior)
ValueError: slice items can have all fixed-size dimensions (to follow NumPy's slice rules) or they can have all var-sized dimensions (for jagged indexing), but not both in the same slice item

(https://github.com/scikit-hep/awkward-1.0/blob/1.10.2/src/libawkward/array/RegularArray.cpp#L982)
```

This may have to do with the progression of awkward array between the image you were using and the latest image. Could you let me know the image where things were working?

**Comment by lgray** [comment]
So a modified version of this that works, appeasing this requirement of "all jagged" or "all fixed-size", I used ak.singletons:
```
from coffea.nanoevents import NanoEventsFactory
import awkward as ak

import warnings
import numpy as np

events = NanoEventsFactory.from_root("root://cmsxrootd.fnal.gov//store/user/lpcpfnano/cmantill/v2_2/2017/HWW/GluGluHToWW_Pt-200ToInf_M-125_TuneCP5_MINLO_13TeV-powheg-pythia8/GluGluHToWW_Pt-200ToInf_M-125\
/220629_181652/0000/nano_mc2017_1-1.root").events()

higgs = events.GenPart[abs(events.GenPart.pdgId)==25 & events.GenPart.hasFlags(['fromHardProcess', 'isLastCopy'])]
higgs = higgs[ ak.all(abs(higgs.children.pdgId) == 24, axis=2) ]
jet = ak.singletons(ak.firsts(events.FatJet))

# this works                                                                                                                                                                                                
print(events.FatJet.nearest(higgs))

# but this doesn't                                                                                                                                                                                          
print(jet.nearest(higgs))
print(jet.nearest(ak.singletons(ak.firsts(higgs))))
```

This produces:
```
[[GenParticle], [GenParticle, GenParticle], ... [], [GenParticle, GenParticle]]
[[GenParticle], [GenParticle], [None], ... [None], [], [GenParticle]]
[[GenParticle], [GenParticle], [None], ... [None], [], [GenParticle]]
```

I'm not sure if you want the "None" matches or not though, since I didn't see the expected outcome.

**Comment by lgray** [comment]
@jpivarski any idea when this rule was introduced in the history of awkward?

**Comment by cmantill** [comment]
Ah so it looks like if I use: 
- `coffeateam/coffea-base-cc7:0.7.20-fastjet-3.4.0.0rc2`: I reproduce the error from my reproducer (and get past the 2nd printout):
```
Singularity> python cristina_test.py 
[[GenParticle], [GenParticle, GenParticle], ... [], [GenParticle, GenParticle]]
[[GenParticle], [GenParticle], [None], ... GenParticle], [None], None, [GenParticle]]
Traceback (most recent call last):
  File "cristina_test.py", line 24, in <module>
    print(jet.nearest(ak.firsts(higgs)))
  File "/usr/local/lib/python3.8/site-packages/coffea/nanoevents/methods/vector.py", line 730, in nearest
    mval, (a, b) = self.metric_table(other, axis, metric, return_combinations=True)
  File "/usr/local/lib/python3.8/site-packages/coffea/nanoevents/methods/vector.py", line 694, in metric_table
    awkward.cartesian([self, other], axis=axis, nested=True)
  File "/usr/local/lib/python3.8/site-packages/awkward/operations/structure.py", line 3562, in cartesian
    out = ak._util.broadcast_and_apply(
  File "/usr/local/lib/python3.8/site-packages/awkward/_util.py", line 1172, in broadcast_and_apply
    out = apply(broadcast_pack(inputs, isscalar), 0, user)
  File "/usr/local/lib/python3.8/site-packages/awkward/_util.py", line 925, in apply
    outcontent = apply(nextinputs, depth + 1, user)
  File "/usr/local/lib/python3.8/site-packages/awkward/_util.py", line 881, in apply
    outcontent = apply(nextinputs, depth, user)
  File "/usr/local/lib/python3.8/site-packages/awkward/_util.py", line 925, in apply
    outcontent = apply(nextinputs, depth + 1, user)
  File "/usr/local/lib/python3.8/site-packages/awkward/_util.py", line 881, in apply
    outcontent = apply(nextinputs, depth, user)
  File "/usr/local/lib/python3.8/site-packages/awkward/_util.py", line 1077, in apply
    raise ValueError(
ValueError: cannot broadcast records because keys don't match:
    DDX_jetNSecondaryVertices, DDX_jetNTracks, DDX_tau1_flightDistance2dSig, DDX_tau1_trackEtaRel_0, DDX_tau1_trackEtaRel_1, DDX_tau1_trackEtaRel_2, DDX_tau1_trackSip3dSig_0, DDX_tau1_trackSip3dSig_1, DDX_tau1_vertexDeltaR, DDX_tau1_vertexEnergyRatio, DDX_tau1_vertexMass, DDX_tau2_flightDistance2dSig, DDX_tau2_trackEtaRel_0, DDX_tau2_trackEtaRel_1, DDX_tau2_trackEtaRel_3, DDX_tau2_trackSip3dSig_0, DDX_tau2_trackSip3dSig_1, DDX_tau2_vertexEnergyRatio, DDX_tau2_vertexMass, DDX_trackSip2dSigAboveBottom_0, DDX_trackSip2dSigAboveBottom_1, DDX_trackSip2dSigAboveCharm, DDX_trackSip3dSig_0, DDX_trackSip3dSig_1, DDX_trackSip3dSig_2, DDX_trackSip3dSig_3, DDX_z_ratio, Proba, area, btagCSVV2, btagDDBvLV2, btagDDCvBV2, btagDDCvLV2, btagDeepB, btagDeepB_b, btagDeepB_bb, btagDeepL, btagHbb, deepTagMD_H4qvsQCD, deepTagMD_HbbvsQCD, deepTagMD_TvsQCD, deepTagMD_WvsQCD, deepTagMD_ZHbbvsQCD, deepTagMD_ZHccvsQCD, deepTagMD_ZbbvsQCD, deepTagMD_ZvsQCD, deepTagMD_bbvsLight, deepTagMD_ccvsLight, deepTag_H, deepTag_QCD, deepTag_QCDothers, deepTag_TvsQCD, deepTag_WvsQCD, deepTag_ZvsQCD, electronIdx3SJ, eta, genJetAK8Idx, genJetAK8IdxG, hadronFlavour, jetId, lsf3, mass, msoftdrop, muonIdx3SJ, n2b1, n3b1, nBHadrons, nCHadrons, nConstituents, pFCandsIdxG, particleNetMD_QCD, particleNetMD_Xbb, particleNetMD_Xcc, particleNetMD_Xqq, particleNet_H4qvsQCD, particleNet_HbbvsQCD, particleNet_HccvsQCD, particleNet_QCD, particleNet_TvsQCD, particleNet_WvsQCD, particleNet_ZvsQCD, particleNet_mass, phi, pt, rawFactor, subJetIdx1, subJetIdx1G, subJetIdx2, subJetIdx2G, subJetIdxG, tau1, tau2, tau3, tau4
    childrenIdxG, distinctChildrenIdxG, distinctParentIdxG, eta, genPartIdxMother, genPartIdxMotherG, mass, pdgId, phi, pt, status, statusFlags

(https://github.com/scikit-hep/awkward-1.0/blob/1.10.1/src/awkward/_util.py#L1082)
```
- but if I use the latest image: `/cvmfs/unpacked.cern.ch/registry.hub.docker.com/coffeateam/coffea-base:latest` - then I am not able to get past: `jet.nearest(higgs)`. 
```
bash-4.2$ ./shell coffeateam/coffea-base:latest
Singularity> python cristina_test.py 
[[GenParticle], [GenParticle, GenParticle], ... [], [GenParticle, GenParticle]]
Traceback (most recent call last):
  File "cristina_test.py", line 23, in <module>
    print(jet.nearest(higgs))
  File "/opt/conda/lib/python3.8/site-packages/coffea/nanoevents/methods/vector.py", line 735, in nearest
    out = awkward.firsts(b[mmin], axis=axis + 1)
  File "/opt/conda/lib/python3.8/site-packages/awkward/highlevel.py", line 991, in __getitem__
    tmp = ak._util.wrap(self.layout[where], self._behavior)
ValueError: slice items can have all fixed-size dimensions (to follow NumPy's slice rules) or they can have all var-sized dimensions (for jagged indexing), but not both in the same slice item

(https://github.com/scikit-hep/awkward-1.0/blob/1.10.2/src/libawkward/array/RegularArray.cpp#L982)
```

I guess I do need to `ak.singletons` after any `ak.firsts`?

**Comment by lgray** [comment]
> I guess I do need to ak.singletons after any ak.firsts?

That seems to be a way around this but I'm not sure if this particular complaint from awkward is expected or not. Neither am I sure if that's giving you the outcome you want in terms of matching! If it's what you want then it's probably good for a workaround, but I'm unsure if it will be robust over time (especially with awkward2 coming up very soon).

There was a bit of funniness with unpinning numpy recently too, not sure how related that can be.... Awkward array didn't change between those two images afaik.

**Comment by lgray** [comment]
Trying also to see if I can fix this within coffea, I'd rather stabilize the interface there.

**Comment by lgray** [comment]
I'm able to reproduce this even with the test files in coffea, and something really strange is happening with `ak.firsts` in this case. However, I think I found a better and more robust way to do your selection in the future, using indices rather than `ak.firsts` which I think has some knockon effects for what you're trying to accomplish.

```python3
from coffea.nanoevents import NanoEventsFactory
import awkward as ak

import warnings
import numpy as np

events = NanoEventsFactory.from_root("root://cmsxrootd.fnal.gov//store/user/lpcpfnano/cmantill/v2_2/2017/HWW/GluGluHToWW_Pt-200ToInf_M-125_TuneCP5_MINLO_13TeV-powheg-pythia8/GluGluHToWW_Pt-200ToInf_M-125\
/220629_181652/0000/nano_mc2017_1-1.root").events()

higgs = events.GenPart[abs(events.GenPart.pdgId)==25 & events.GenPart.hasFlags(['fromHardProcess', 'isLastCopy'])]
higgs = higgs[ ak.all(abs(higgs.children.pdgId) == 24, axis=2) ]
jet = events.FatJet[:, :1]

# this works                                                                                                                                                                                                
print(events.FatJet.nearest(higgs))

# but this also works                                                                                                                                                                                
print(jet.nearest(higgs))
print(jet.nearest(higgs[:, :1]))
```

This will always work and does exactly what you were doing before.

**Comment by lgray** [comment]
I'll dig into why `ak.firsts` is causing problems.

**Comment by lgray** [comment]
@jpivarski - somehow I am getting a type like:
```
40 * ?fatJet
40 * ?genParticle
```

and it is producing the error:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "tests/test_750.py", line 25, in test_750
    print(jet.nearest(ak.firsts(higgs)))
  File "/Users/lgray/coffea-testing/coffea/coffea/nanoevents/methods/vector.py", line 734, in nearest
    mval, (a, b) = self.metric_table(other, axis, metric, return_combinations=True)
  File "/Users/lgray/coffea-testing/coffea/coffea/nanoevents/methods/vector.py", line 694, in metric_table
    awkward.cartesian([self, other], axis=axis, nested=True)
  File "/Users/lgray/miniforge3/envs/coffea-testing/lib/python3.8/site-packages/awkward/operations/structure.py", line 3562, in cartesian
    out = ak._util.broadcast_and_apply(
  File "/Users/lgray/miniforge3/envs/coffea-testing/lib/python3.8/site-packages/awkward/_util.py", line 1172, in broadcast_and_apply
    out = apply(broadcast_pack(inputs, isscalar), 0, user)
  File "/Users/lgray/miniforge3/envs/coffea-testing/lib/python3.8/site-packages/awkward/_util.py", line 925, in apply
    outcontent = apply(nextinputs, depth + 1, user)
  File "/Users/lgray/miniforge3/envs/coffea-testing/lib/python3.8/site-packages/awkward/_util.py", line 881, in apply
    outcontent = apply(nextinputs, depth, user)
  File "/Users/lgray/miniforge3/envs/coffea-testing/lib/python3.8/site-packages/awkward/_util.py", line 925, in apply
    outcontent = apply(nextinputs, depth + 1, user)
  File "/Users/lgray/miniforge3/envs/coffea-testing/lib/python3.8/site-packages/awkward/_util.py", line 881, in apply
    outcontent = apply(nextinputs, depth, user)
  File "/Users/lgray/miniforge3/envs/coffea-testing/lib/python3.8/site-packages/awkward/_util.py", line 1077, in apply
    raise ValueError(
ValueError: cannot broadcast records because keys don't match:
    area, btagCMVA, btagCSVV2, btagDDBvL, btagDDBvL_noMD, btagDDCvB, btagDDCvB_noMD, btagDDCvL, btagDDCvL_noMD, btagDeepB, btagHbb, deepTagMD_H4qvsQCD, deepTagMD_HbbvsQCD, deepTagMD_TvsQCD, deepTagMD_WvsQCD, deepTagMD_ZHbbvsQCD, deepTagMD_ZHccvsQCD, deepTagMD_ZbbvsQCD, deepTagMD_ZvsQCD, deepTagMD_bbvsLight, deepTagMD_ccvsLight, deepTag_H, deepTag_QCD, deepTag_QCDothers, deepTag_TvsQCD, deepTag_WvsQCD, deepTag_ZvsQCD, eta, jetId, mass, msoftdrop, n2b1, n3b1, phi, pt, rawFactor, subJetIdx1, subJetIdx1G, subJetIdx2, subJetIdx2G, subJetIdxG, tau1, tau2, tau3, tau4
    childrenIdxG, distinctChildrenIdxG, distinctParentIdxG, eta, genPartIdxMother, genPartIdxMotherG, mass, pdgId, phi, pt, status, statusFlags
```

when calling:
```
awkward.cartesian([array1, array2], axis=2, nested=True)
```

This seems like incorrect behavior, especially since this worked in the past. Any idea on how to explore this a little better?

**Comment by jpivarski** [comment]
If the types really are

```
40 * ?fatJet
40 * ?genParticle
```

then it seems correct to me. The deepest `axis` you can use in `ak.cartesian` on one-dimensional arrays of records (with different fields) is `0`.

```python
>>> one = ak.Array([{"x": 1, "y": 10}, {"x": 2, "y": 20}, None])
>>> two = ak.Array([{"a": 1.1, "b": 11}, None, {"c": 2.2, "d": 22}])

>>> ak.cartesian([one, two], axis=0).show()
[({x: 1, y: 10}, {a: 1.1, b: 11, c: ..., ...}),
 ({x: 1, y: 10}, None),
 ({x: 1, y: 10}, {a: None, b: None, ...}),
 ({x: 2, y: 20}, {a: 1.1, b: 11, c: ..., ...}),
 ({x: 2, y: 20}, None),
 ({x: 2, y: 20}, {a: None, b: None, ...}),
 (None, {a: 1.1, b: 11, c: None, ...}),
 (None, None),
 (None, {a: None, b: None, c: 2.2, ...})]

>>> ak.cartesian([one, two], axis=1).show()
Traceback (most recent call last):
...
ValueError: while calling

    ak.cartesian(
        arrays = [<Array [{x: 1, y: 10}, {...}, None] type='3 * ?{x: int64, y...
        axis = 1
        nested = None
        parameters = None
        with_name = None
        highlevel = True
        behavior = None
    )

Error details: cannot broadcast records because fields don't match:
    x, y
    a, b, c, d
```

If the arrays are one level deeper, however, you can go one `axis` deeper:

```python
>>> one = ak.Array([[{"x": 1, "y": 10}], [{"x": 2, "y": 20}, None]])
>>> two = ak.Array([[{"a": 1.1, "b": 11}, None], [{"c": 2.2, "d": 22}]])

>>> ak.cartesian([one, two], axis=0).show()
[([{x: 1, y: 10}], [{a: 1.1, ...}, None]),
 ([{x: 1, y: 10}], [{a: None, b: None, ...}]),
 ([{x: 2, y: 20}, None], [{a: 1.1, ...}, ...]),
 ([{x: 2, y: 20}, None], [{a: None, b: ..., ...}])]

>>> ak.cartesian([one, two], axis=1).show()
[[({x: 1, y: 10}, {a: 1.1, b: 11, ...}), ({x: 1, ...}, None)],
 [({x: 2, y: 20}, {a: None, b: None, ...}), (None, {...})]]

>>> ak.cartesian([one, two], axis=2).show()
Traceback (most recent call last):
...
ValueError: while calling

    ak.cartesian(
        arrays = [<Array [[{x: 1, y: 10}], [{...}, ...]] type='2 * var * ?{x:...
        axis = 2
        nested = None
        parameters = None
        with_name = None
        highlevel = True
        behavior = None
    )
```

And again with another level, to allow `axis=2`:

```python
>>> one = ak.Array([[[{"x": 1, "y": 10}], []], [[{"x": 2, "y": 20}, None]]])
>>> two = ak.Array([[[{"a": 1.1, "b": 11}], []], [[{"c": 2.2, "d": 22}, None]]])

>>> ak.cartesian([one, two], axis=0).show()
[([[{x: 1, y: 10}], []], [[{a: 1.1, ...}], ...]),
 ([[{x: 1, y: 10}], []], [[{a: None, ...}, ...]]),
 ([[{x: 2, y: 20}, None]], [[{a: 1.1, ...}], ...]),
 ([[{x: 2, y: 20}, None]], [[{a: None, ...}, ...]])]

>>> ak.cartesian([one, two], axis=1).show()
[[([{x: 1, y: 10}], [{a: 1.1, b: 11, ...}]), ([{...}], ...), ..., ([], [])],
 [([{x: 2, y: 20}, None], [{a: None, ...}, ...])]]

>>> ak.cartesian([one, two], axis=2).show()
[[[({x: 1, y: 10}, {a: 1.1, b: 11, ...})], []],
 [[({x: 2, y: 20}, {a: None, b: None, ...}), ({...}, ...), ..., (None, None)]]]

>>> ak.cartesian([one, two], axis=3).show()
Traceback (most recent call last):
...
ValueError: while calling

    ak.cartesian(
        arrays = [<Array [[[{x: 1, y: 10}], []], [[...]]] type='2 * var * var...
        axis = 3
        nested = None
        parameters = None
        with_name = None
        highlevel = True
        behavior = None
    )

Error details: cannot broadcast records because fields don't match:
    x, y
    a, b, c, d
```

**Comment by lgray** [comment]
Yeah - indeed - looking at this a bit more `ak.firsts` seems to be not really the thing we wanted... I'm curious how this was getting a correct outcome in the past. `ak.firsts` has removed the dimension it acted over since its inception, right?

**Comment by jpivarski** [comment]
The `ak.firsts`/`ak.singletons` might be the problem. We wanted to put more thought into them in v2 (see https://github.com/scikit-hep/awkward/issues/983#issuecomment-875987507) and I don't know that we did. I'm going to make a `next-release` (i.e. high priority) issue to check that these functions are sensible and make them so if not. They don't even have an `axis` parameter, the last time I checked.

**Comment by lgray** [comment]
In any case - I think the `[:, :1]` notation is actually best choice for what @cmantill wants to accomplish here. 

We may need to do a bit of archaeology to understand what was going right or wrong in the past that led to this issue being opened.

**Comment by jpivarski** [comment]
`ak.firsts` is supposed to remove a dimension. `ak.firsts(array)` is supposed to be like `array[:, 0]` but return option-type with `None` instead of an exception for any empty lists. Thus, it does (is supposed to) reduce a dimension.

Edit: `array[:, :1]` would do the same thing except return non-option-type with `[]` instead of an exception for empty lists.

**Comment by lgray** [comment]
Yeah - and that jagged shape is the correct one for making tables of nearests.

**Comment by cmantill** [comment]
@lgray thanks! I agree that `array[:, 1]` accomplishes what I was trying to do here - and that that jagged shape works. 

I should emphasize that at no point I was trying to do: `jet.nearest(ak.firsts(higgs))`. So this won't work on any image.

But `ak.firsts(events.FatJet).nearest(higgs)` does fail in the latest image and works in `coffeateam/coffea-base-cc7:0.7.20-fastjet-3.4.0.0rc2`.

**Comment by lgray** [comment]
ahhhha thanks for the clarification!

**Comment by lgray** [comment]
@cmantill FYI - I tried running the reproducer in `coffeateam/coffea-base-cc7:0.7.20-fastjet-3.4.0.0rc2` and it failed in the same way as with the latest image.
