### ISSUE TITLE
Numba: use of unsupported opcode in LumiMask with dask executor on CERNCluster

### ISSUE THREAD

**Issue by patinkaew** [scikit-hep/coffea#769]
**Describe the bug**
Numba: use of unsupported opcode in LumiMask._apply_run_lumi_mask_kernel on CERNCluster with Dask 

**To Reproduce**
```
lumimask = LumiMask(lumi_json_path)
events = events[lumimask(events.run, events.luminosityBlock)]
```
Run on lxplus with dask through dask-lxplus. There is no error when running with Iterative or Future executor on local machine.

**Expected behavior**
No error. (No error in case of Iterative / Future executor run on local machine)

**Output**
```
Traceback (most recent call last):       ] | 50% Completed | 22.6sn  4.2s
  File "/eos/home-p/pinkaew/research/online-offline-jec/process.py", line 353, in <module>
    processing(args, configs, runner, fileset, treename="Events", 
  File "/eos/home-p/pinkaew/research/online-offline-jec/process.py", line 83, in processing
    out = runner(fileset, treename=treename, processor_instance=processor_instance)
  File "/cvmfs/sft.cern.ch/lcg/views/LCG_102/x86_64-centos7-gcc11-opt/lib/python3.9/site-packages/coffea/processor/executor.py", line 1366, in __call__
    wrapped_out = executor(chunks, closure, None)
  File "/cvmfs/sft.cern.ch/lcg/views/LCG_102/x86_64-centos7-gcc11-opt/lib/python3.9/site-packages/coffea/processor/executor.py", line 735, in __call__
    else _decompress(work.result())
  File "/cvmfs/sft.cern.ch/lcg/views/LCG_102/x86_64-centos7-gcc11-opt/lib/python3.9/site-packages/distributed/client.py", line 275, in result
    raise exc.with_traceback(tb)
  File "/cvmfs/sft.cern.ch/lcg/views/LCG_102/x86_64-centos7-gcc11-opt/lib/python3.9/site-packages/coffea/processor/executor.py", line 197, in __call__
    out = self.function(*args, **kwargs)
  File "/cvmfs/sft.cern.ch/lcg/views/LCG_102/x86_64-centos7-gcc11-opt/lib/python3.9/site-packages/coffea/processor/executor.py", line 990, in automatic_retries
    raise e
  File "/cvmfs/sft.cern.ch/lcg/views/LCG_102/x86_64-centos7-gcc11-opt/lib/python3.9/site-packages/coffea/processor/executor.py", line 978, in automatic_retries
    return func(*args, **kwargs)
  File "/cvmfs/sft.cern.ch/lcg/views/LCG_102/x86_64-centos7-gcc11-opt/lib/python3.9/site-packages/coffea/processor/executor.py", line 1238, in _work_function
    raise type(e)(str(e) + file_trace).with_traceback(
  File "/cvmfs/sft.cern.ch/lcg/views/LCG_102/x86_64-centos7-gcc11-opt/lib/python3.9/site-packages/coffea/processor/executor.py", line 1235, in _work_function
    out = processor_instance.process(events)
  File "/tmp/dask-worker-space/worker-_6baxrgg/processor.zip/processor/processor.py", line 264, in process
  File "/cvmfs/sft.cern.ch/lcg/views/LCG_102/x86_64-centos7-gcc11-opt/lib/python3.9/site-packages/coffea/lumi_tools/lumi_tools.py", line 130, in __call__
    LumiMask._apply_run_lumi_mask_kernel(_masks, runs, lumis, mask_out)
  File "/cvmfs/sft.cern.ch/lcg/views/LCG_102/x86_64-centos7-gcc11-opt/lib/python3.9/site-packages/numba/core/dispatcher.py", line 418, in _compile_for_args
    error_rewrite(e, 'unsupported_error')
  File "/cvmfs/sft.cern.ch/lcg/views/LCG_102/x86_64-centos7-gcc11-opt/lib/python3.9/site-packages/numba/core/dispatcher.py", line 358, in error_rewrite
    reraise(type(e), e, None)
  File "/cvmfs/sft.cern.ch/lcg/views/LCG_102/x86_64-centos7-gcc11-opt/lib/python3.9/site-packages/numba/core/utils.py", line 80, in reraise
    raise value.with_traceback(tb)
numba.core.errors.UnsupportedError: Failed in nopython mode pipeline (step: analyzing bytecode)
Use of unsupported opcode (CONTAINS_OP) found

File "../../../cvmfs/sft.cern.ch/lcg/views/LCG_102/x86_64-centos7-gcc11-opt/lib/python3.9/site-packages/coffea/lumi_tools/lumi_tools.py", line 141:
    def _apply_run_lumi_mask_kernel(masks, runs, lumis, mask_out):
        <source elided>

            if run in masks:
```

**Desktop (please complete the following information):**
lxplus7104, LCG102, HTCondor v9.0

**Comment by lgray** [comment]
This is not a problem in coffea. This is a numba vs. python version misalignment (I don't even know how LCG managed to ship this release in this case). Numba 0.51.2 does not support python 3.9. 

You can switch to LCG_103, which contains numba 0.55 and python 3.9 which are compatible.,

**Comment by patinkaew** [comment]
Thank you! After switching to LCG_103, it works!
