### ISSUE TITLE
In LumiData: numba no implementation of function

### ISSUE THREAD

**Issue by patinkaew** [scikit-hep/coffea#770]
**Describe the bug**
Problem with numba in LumiData: no implementation of function setitem found for given signature

**To Reproduce**
```
lumidata = LumiData(lumi_csv_path)
lumidata.get_lumi(lumi_accumulator)
```
Run with dask executor on CERNcluster through dask-lxplus. Observe no error when running with Iterative/Future executor on local machine.

**Expected behavior**
No error

**Output**
```
Traceback (most recent call last):#######] | 100% Completed | 18.0s 34.9s
  File "/eos/home-p/pinkaew/research/online-offline-jec/process.py", line 353, in <module>
    processing(args, configs, runner, fileset, treename="Events", 
  File "/eos/home-p/pinkaew/research/online-offline-jec/process.py", line 83, in processing
    out = runner(fileset, treename=treename, processor_instance=processor_instance)
  File "/cvmfs/sft.cern.ch/lcg/views/LCG_102/x86_64-centos7-gcc11-opt/lib/python3.9/site-packages/coffea/processor/executor.py", line 1368, in __call__
    processor_instance.postprocess(wrapped_out["out"])
  File "/eos/home-p/pinkaew/research/online-offline-jec/processor/processor.py", line 678, in postprocess
    accumulator["processed_lumi"][dataset]["lumi"] = lumidata.get_lumi(accumulator["processed_lumi"][dataset]["lumi_list"])
  File "/cvmfs/sft.cern.ch/lcg/views/LCG_102/x86_64-centos7-gcc11-opt/lib/python3.9/site-packages/coffea/lumi_tools/lumi_tools.py", line 53, in get_lumi
    LumiData._build_lumi_table_kernel(runs, lumis, self._lumidata, self.index)
  File "/cvmfs/sft.cern.ch/lcg/views/LCG_102/x86_64-centos7-gcc11-opt/lib/python3.9/site-packages/numba/core/dispatcher.py", line 415, in _compile_for_args
    error_rewrite(e, 'typing')
  File "/cvmfs/sft.cern.ch/lcg/views/LCG_102/x86_64-centos7-gcc11-opt/lib/python3.9/site-packages/numba/core/dispatcher.py", line 358, in error_rewrite
    reraise(type(e), e, None)
  File "/cvmfs/sft.cern.ch/lcg/views/LCG_102/x86_64-centos7-gcc11-opt/lib/python3.9/site-packages/numba/core/utils.py", line 80, in reraise
    raise value.with_traceback(tb)
numba.core.errors.TypingError: Failed in nopython mode pipeline (step: nopython frontend)
No implementation of function Function(<built-in function setitem>) found for signature:
 
 >>> setitem(DictType[UniTuple(uint32 x 2),float64]<iv=None>, UniTuple(uint32 x 2), float64)
 
There are 16 candidate implementations:
  - Of which 14 did not match due to:
  Overload of function 'setitem': File: <numerous>: Line N/A.
    With argument(s): '(DictType[UniTuple(uint32 x 2),float64]<iv=None>, UniTuple(uint32 x 2), float64)':
   No match.
  - Of which 2 did not match due to:
  Overload in function 'impl_setitem': File: numba/typed/dictobject.py: Line 671.
    With argument(s): '(DictType[UniTuple(uint32 x 2),float64]<iv=None>, UniTuple(uint32 x 2), float64)':
   Rejected as the implementation raised a specific error:
     TypingError: Failed in nopython mode pipeline (step: nopython frontend)
   No implementation of function Function(<built-in function hash>) found for signature:
    
    >>> hash(UniTuple(uint32 x 2))
    
   There are 2 candidate implementations:
         - Of which 2 did not match due to:
         Overload in function 'hash_overload': File: numba/cpython/hashing.py: Line 46.
           With argument(s): '(UniTuple(uint32 x 2))':
          Rejected as the implementation raised a specific error:
            TypingError: Failed in nopython mode pipeline (step: nopython frontend)
          - Resolution failure for literal arguments:
          No implementation of function Function(<function tuple_hash at 0x7f0c9b4a4b80>) found for signature:
          
           >>> tuple_hash(UniTuple(uint32 x 2))
          
          There are 2 candidate implementations:
                - Of which 2 did not match due to:
                Overload in function 'tuple_hash': File: numba/cpython/hashing.py: Line 354.
                  With argument(s): '(UniTuple(uint32 x 2))':
                 Rejected as the implementation raised a specific error:
                   TypingError: Failed in nopython mode pipeline (step: nopython frontend)
                 No implementation of function Function(<function _tuple_hash at 0x7f0c9b4a4940>) found for signature:
          
                  >>> _tuple_hash(UniTuple(uint32 x 2))
          
                 There are 2 candidate implementations:
                       - Of which 2 did not match due to:
                       Overload in function 'register_jitable.<locals>.wrap.<locals>.ov_wrap': File: numba/core/extending.py: Line 150.
                         With argument(s): '(UniTuple(uint32 x 2))':
                        Rejected as the implementation raised a specific error:
                          UnsupportedError: Failed in nopython mode pipeline (step: handles literal_unroll)
                        Failed in literal_unroll_subpipeline mode pipeline (step: performs mixed container unroll)
                        Use of unsupported opcode (CONTAINS_OP) found
          
                        File "<string>", line 2:
                        <source missing, REPL/exec in use?>
          
                   raised from /cvmfs/sft.cern.ch/lcg/views/LCG_102/x86_64-centos7-gcc11-opt/lib/python3.9/site-packages/numba/core/byteflow.py:269
          
                 During: resolving callee type: Function(<function _tuple_hash at 0x7f0c9b4a4940>)
                 During: typing of call at /cvmfs/sft.cern.ch/lcg/views/LCG_102/x86_64-centos7-gcc11-opt/lib/python3.9/site-packages/numba/cpython/hashing.py (358)
          
          
                 File "../../../../../cvmfs/sft.cern.ch/lcg/views/LCG_102/x86_64-centos7-gcc11-opt/lib/python3.9/site-packages/numba/cpython/hashing.py", line 358:
                         def impl(val):
                             return _tuple_hash(val)
                             ^
          
            raised from /cvmfs/sft.cern.ch/lcg/views/LCG_102/x86_64-centos7-gcc11-opt/lib/python3.9/site-packages/numba/core/typeinfer.py:1071
          
          - Resolution failure for non-literal arguments:
          None
          
          During: resolving callee type: BoundFunction((<class 'numba.core.types.containers.BaseTuple'>, '__hash__') for UniTuple(uint32 x 2))
          During: typing of call at /cvmfs/sft.cern.ch/lcg/views/LCG_102/x86_64-centos7-gcc11-opt/lib/python3.9/site-packages/numba/cpython/hashing.py (49)
          
          
          File "../../../../../cvmfs/sft.cern.ch/lcg/views/LCG_102/x86_64-centos7-gcc11-opt/lib/python3.9/site-packages/numba/cpython/hashing.py", line 49:
              def impl(obj):
                  return obj.__hash__()
                  ^
   
     raised from /cvmfs/sft.cern.ch/lcg/views/LCG_102/x86_64-centos7-gcc11-opt/lib/python3.9/site-packages/numba/core/typeinfer.py:1071
   
   During: resolving callee type: Function(<built-in function hash>)
   During: typing of call at /cvmfs/sft.cern.ch/lcg/views/LCG_102/x86_64-centos7-gcc11-opt/lib/python3.9/site-packages/numba/typed/dictobject.py (681)
   
   
   File "../../../../../cvmfs/sft.cern.ch/lcg/views/LCG_102/x86_64-centos7-gcc11-opt/lib/python3.9/site-packages/numba/typed/dictobject.py", line 681:
       def impl(d, key, value):
           <source elided>
           castedval = _cast(value, valty)
           status = _dict_insert(d, castedkey, hash(castedkey), castedval)
           ^

  raised from /cvmfs/sft.cern.ch/lcg/views/LCG_102/x86_64-centos7-gcc11-opt/lib/python3.9/site-packages/numba/core/typeinfer.py:1071

During: typing of setitem at /cvmfs/sft.cern.ch/lcg/views/LCG_102/x86_64-centos7-gcc11-opt/lib/python3.9/site-packages/coffea/lumi_tools/lumi_tools.py (67)

File "../../../../../cvmfs/sft.cern.ch/lcg/views/LCG_102/x86_64-centos7-gcc11-opt/lib/python3.9/site-packages/coffea/lumi_tools/lumi_tools.py", line 67:
    def _build_lumi_table_kernel(runs, lumis, lumidata, index):
        <source elided>
            lumi = lumis[i]
            index[(run, lumi)] = float(lumidata[i, 2])
            ^
```

**Desktop (please complete the following information):**
lxplu7104, LCG102, HTCondor v9.0

**Additional context**
```lumidata.get_lumi(lumi_accumulator)``` is called inside postprocess method of a processor. 
I implement LumiAccumulator which inherits from LumiList.:
```
import numpy as np
from coffea.lumi_tools import LumiList

class LumiAccumulator(LumiList): # extention of coffea lumi list
    def __init__(self, runs=None, lumis=None, auto_unique=False):
        super().__init__(runs, lumis)
        self.auto_unique = auto_unique
    
    def unique(self):
        if len(self.array) > 0:
            self.array = np.unique(self.array, axis=0)
            
    def __add__(self, other):
        lumi_acc = LumiAccumulator()
        lumi_acc.array = np.r_[self.array, other.array]
        if self.auto_unique:
            lumi_acc.unique()
        return lumi_acc
    
    def __iadd__(self, other):
        super().__iadd__(other)
        if self.auto_unique:
            self.unique()
        return self
            
    __radd__ = __iadd__
```

**Comment by patinkaew** [comment]
From related issue: [CoffeaTeam/coffea#769](https://github.com/CoffeaTeam/coffea/issues/769), switching to LCG_103 seems to solve this issue as well.
