### ISSUE TITLE
Failure to pickle when using `defaultdict` and a custom class as `Processor` attribute (0.7.21)

### ISSUE THREAD

**Issue by MoAly98** [scikit-hep/coffea#865]
**Describe the bug**

It seems like when using `defaultdict` in a processor and simply adding a custom class as a processor attribute (without even using it), the pickling fails with a `FuturesExecutor`.

**To Reproduce**
```
from coffea import processor
from coffea.nanoevents import  BaseSchema
import os
from glob import glob
from collections import defaultdict


class Functor(object):
    def __init__(self, fn, args):
        self.fn = fn
        self.args = args
        assert isinstance(self.args, list)

    def evaluate(self, data):
        data_args = [data[arg] for arg in self.args]
        return self.fn(*data_args)

class Plots(object):
    def __init__(self, dim, tree, to_plot = []):
        if dim != 1 and dim != 2:
            print("ERROR:: Supporting only 1D and 2D plots")
            exit()
        self.dim = dim
        self.tree = tree
        self.to_plot = to_plot

    def append(self, plot_histo):
        plot_histo.set_dim(self.dim)
        self.to_plot.append(plot_histo)

class Plot(object):
    def __init__(self, name, howto, binning):
        self.name = name
        self.howto = howto
        self.binning = binning


class MyProcessor(processor.ProcessorABC):

    def __init__(self, plots = []):
        self.plots =    plots

    def dd(self):
        return defaultdict(dict)

    def process(self, presel_events):

        output_1d = defaultdict(self.dd)
        dataset = presel_events.metadata['dataset']
        
        return {dataset: {'1D': output_1d}}

    def postprocess(self, accumulator):
        pass


myplot = Plot('new_bdt_tH', Functor(lambda x: x[:,0], ['BDT']), [0, 0.3528, 0.6, 0.78, 1])
plots_list = [ Plots(1, 'nominal_Loose', myplot) ]

if __name__ == '__main__':

    fileset = {'MySample': glob('MyFilePath.root')}
    executor = processor.FuturesExecutor(workers=1)
    run = processor.Runner(executor=executor, metadata_cache={}, schema=BaseSchema, skipbadfiles=True, maxchunks=1)
    _ = run(fileset, 'nominal_Loose', MyProcessor(plots_list)  )

    print(_)

```

**Output**

The processing seems to finish, but when the merging starts, I get:

```
concurrent.futures.process._RemoteTraceback:
"""
Traceback (most recent call last):
  File "/eos/user/m/maly/conda_envs/miniconda3/lib/python3.8/concurrent/futures/process.py", line 239, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
  File "/eos/user/m/maly/conda_envs/miniconda3/lib/python3.8/site-packages/coffea/processor/executor.py", line 222, in __call__
    return _compress(out, self.level)
  File "/eos/user/m/maly/conda_envs/miniconda3/lib/python3.8/site-packages/coffea/processor/executor.py", line 186, in _compress
    pickle.dump(item, f, protocol=_PICKLE_PROTOCOL)
_pickle.PicklingError: Can't pickle <function <lambda> at 0x7fb390b36e50>: attribute lookup <lambda> on __main__ failed
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/eos/user/m/maly/conda_envs/miniconda3/lib/python3.8/site-packages/coffea/processor/executor.py", line 786, in _processwith
    merged = _watcher(FH, self, reducer, pool)
  File "/eos/user/m/maly/conda_envs/miniconda3/lib/python3.8/site-packages/coffea/processor/executor.py", line 402, in _watcher
    batch = FH.fetch(len(FH.completed))
  File "/eos/user/m/maly/conda_envs/miniconda3/lib/python3.8/site-packages/coffea/processor/executor.py", line 286, in fetch
    raise bad_futures[0].exception()
_pickle.PicklingError: Can't pickle <function <lambda> at 0x7fb390b36e50>: attribute lookup <lambda> on __main__ failed
Traceback (most recent call last):
  File "mwe3.py", line 73, in <module>
    _ = run(fileset, 'nominal_Loose', MyProcessor(plots_list)  )
  File "/eos/user/m/maly/conda_envs/miniconda3/lib/python3.8/site-packages/coffea/processor/executor.py", line 1700, in __call__
    wrapped_out = self.run(fileset, processor_instance, treename)
  File "/eos/user/m/maly/conda_envs/miniconda3/lib/python3.8/site-packages/coffea/processor/executor.py", line 1848, in run
    wrapped_out, e = executor(chunks, closure, None)
  File "/eos/user/m/maly/conda_envs/miniconda3/lib/python3.8/site-packages/coffea/processor/executor.py", line 817, in __call__
    return _processwith(pool=poolinstance, mergepool=mergepoolinstance)
  File "/eos/user/m/maly/conda_envs/miniconda3/lib/python3.8/site-packages/coffea/processor/executor.py", line 801, in _processwith
    raise e from None
  File "/eos/user/m/maly/conda_envs/miniconda3/lib/python3.8/site-packages/coffea/processor/executor.py", line 786, in _processwith
    merged = _watcher(FH, self, reducer, pool)
  File "/eos/user/m/maly/conda_envs/miniconda3/lib/python3.8/site-packages/coffea/processor/executor.py", line 402, in _watcher
    batch = FH.fetch(len(FH.completed))
  File "/eos/user/m/maly/conda_envs/miniconda3/lib/python3.8/site-packages/coffea/processor/executor.py", line 286, in fetch
    raise bad_futures[0].exception()
_pickle.PicklingError: Can't pickle <function <lambda> at 0x7fb390b36e50>: attribute lookup <lambda> on __main__ failed
```
**Desktop (please complete the following information):**
 - OS: Linux
 - Version CentOS-7
 - Coffea: 0.7.21 

**Additional context**

The problem seems to exist if I switch a `defaultdict` for a regular `dict` (inlcuding if I change the return to `{dataset: {'1D': dict(output_1d)}}`) or if I don't pass `plots_list` to the constructor of the processor. In the latter setup, I can still use `plots_list` from the global scope without an error.

**Comment by lgray** [comment]
@MoAly98 looks like this is caused by:
https://github.com/CoffeaTeam/coffea/blob/backports-v0.7.x/coffea/processor/executor.py#L180-L199

Could you try installing coffea 0.7 from source (`git checkout https://github.com/CoffeaTeam/coffea.git -b backports-v0.7.x` and then `pip install -e .` in that directory) and then editing those lines to use cloudpickle instead of pickle?

**Comment by lgray** [comment]
Also please make your reproducer copy/pastable or otherwise explain what you want to achieve.
From the code you've pasted here there's no good reason to do things this way (you should just make histograms on output and add them). 

So it's not entirely clear why you need defaultdict in the first place, as Plot appears to not do much more than hist (and it's unclear if the additional things it does are useful).

**Comment by nsmith-** [comment]
Is this part accurate?
```python
class MyProcessor(processor.ProcessorABC):

    def __init__(self, plots = []):
        self.plots =    plots

    def dd(self):
        return defaultdict(dict)

    def process(self, presel_events):

        output_1d = defaultdict(self.dd)
        dataset = presel_events.metadata['dataset']
        
        return {dataset: {'1D': output_1d}}
```
because I don't see it returning your `Plots` container. Anyway, the container needs to have also an `__add__` defined to be reducible in the next step. Does this code run with `IterativeExecutor`?

**Comment by lgray** [comment]
This seems to have died, was there any resolution?

**Comment by lgray** [comment]
Since this appears stale and is no longer pertinent in dask-awkward / coffea 2023 I'm closing this.
