### ISSUE TITLE
Troubles with coffea installation 

### ISSUE THREAD

**Issue by rdelliga** [scikit-hep/coffea#881]
Hi, I'm on the LPC cluster and I'am trying to install coffea by following the istruction at the link https://coffeateam.github.io/coffea/installation.html#virtual-environment. I entered this code:                                
```
source /cvmfs/sft.cern.ch/lcg/views/LCG_98python3/x86_64-centos7-gcc9-opt/setup.sh
python -m venv my_env
source my_env/bin/activate
pip install coffea
```
but i have the following error: 
```
Collecting coffea
  Using cached https://files.pythonhosted.org/packages/3d/2d/fb0d4577a096bcbee87c15cd57a005a502ca67afcbf19e4d6c7e4d04bef1/coffea-0.7.21-py2.py3-none-any.whl
Collecting uproot3>=3.14.1 (from coffea)
  Using cached 
https://files.pythonhosted.org/packages/9c/69/d893c6eba0dd0d8f82d841d4b85b6e63c52a1b472aec7cf7ae0efedf5a92/uproot3-3.14.4-py3-none-any.whl
Collecting lz4 (from coffea)
  Downloading https://files.pythonhosted.org/packages/9f/54/32b2d68d25b80ae4037cd1c68b8a6a28c6753cba3632cbf6d64bebd2b200/lz4-4.3.2.tar.gz (170kB)
     |████████████████████████████████| 174kB 21.0MB/s
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Requirement already satisfied: pandas in /cvmfs/sft.cern.ch/lcg/views/LCG_98python3/x86_64-centos7-gcc9-opt/lib/python3.7/site-packages (from coffea) (0.24.2)
Collecting toml>=0.10.2 (from coffea)
  Downloading https://files.pythonhosted.org/packages/44/6f/7120676b6d73228c96e17f1f794d8ab046fc910d781c8d151120c3f1569e/toml-0.10.2-py2.py3-none-any.whl
Collecting typing-extensions; python_version < "3.8" (from coffea)
  Using cached https://files.pythonhosted.org/packages/ec/6b/63cc3df74987c36fe26157ee12e09e8f9db4de771e0f3404263117e75b95/typing_extensions-4.7.1-py3-none-any.whl
Collecting correctionlib>=2.0.0 (from coffea)
  Using cached https://files.pythonhosted.org/packages/d7/a4/221534a863f2390d9c4011b68c819bc67537c17d6b2e82641437904886ff/correctionlib-2.2.2.tar.gz
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Requirement already satisfied: matplotlib>=3 in /cvmfs/sft.cern.ch/lcg/views/LCG_98python3/x86_64-centos7-gcc9-opt/lib/python3.7/site-packages (from coffea) (3.1.0)
Collecting numba>=0.56.0; python_version > "3.6" (from coffea)
  Using cached https://files.pythonhosted.org/packages/e2/1e/de917b683bb5f0b6078fb1397293eab84c4eaa825fbf94d73d6488eb354f/numba-0.56.4.tar.gz
Collecting hist>=2 (from coffea)
  Downloading https://files.pythonhosted.org/packages/3a/8a/0ac9bff883dd88f04a16b25ff09653123cf0877f47d42d5021f2b53015a1/hist-2.7.1-py3-none-any.whl (40kB)
     |████████████████████████████████| 40kB 1.7MB/s
Requirement already satisfied: cachetools in /cvmfs/sft.cern.ch/lcg/views/LCG_98python3/x86_64-centos7-gcc9-opt/lib/python3.7/site-packages (from coffea) (3.1.1)
Requirement already satisfied: packaging in /cvmfs/sft.cern.ch/lcg/views/LCG_98python3/x86_64-centos7-gcc9-opt/lib/python3.7/site-packages (from coffea) (19.0)
Collecting uproot3-methods>=0.10.0 (from coffea)
  Downloading https://files.pythonhosted.org/packages/3f/57/598207abeb64bf3e0af3fdc19217e56936b6bebabaac6ee270fb151790ce/uproot3_methods-0.10.1-py3-none-any.whl
Collecting awkward<2,>=1.10.3 (from coffea)
  Using cached https://files.pythonhosted.org/packages/05/0e/c31ea5dd116b3d9fd881cae0ed13e389de77a7d8f72766b12e9ba5217a3c/awkward-1.10.4.tar.gz
ERROR: Exception:
Traceback (most recent call last):
  File "/cvmfs/sft.cern.ch/lcg/views/LCG_98python3/x86_64-centos7-gcc9-opt/lib/python3.7/site-packages/pip/_internal/cli/base_command.py", line 178, in main
    status = self.run(options, args)
  File "/cvmfs/sft.cern.ch/lcg/views/LCG_98python3/x86_64-centos7-gcc9-opt/lib/python3.7/site-packages/pip/_internal/commands/install.py", line 352, in run
    resolver.resolve(requirement_set)
  File "/cvmfs/sft.cern.ch/lcg/views/LCG_98python3/x86_64-centos7-gcc9-opt/lib/python3.7/site-packages/pip/_internal/resolve.py", line 131, in resolve
    self._resolve_one(requirement_set, req)
  File "/cvmfs/sft.cern.ch/lcg/views/LCG_98python3/x86_64-centos7-gcc9-opt/lib/python3.7/site-packages/pip/_internal/resolve.py", line 294, in _resolve_one
    abstract_dist = self._get_abstract_dist_for(req_to_install)
  File "/cvmfs/sft.cern.ch/lcg/views/LCG_98python3/x86_64-centos7-gcc9-opt/lib/python3.7/site-packages/pip/_internal/resolve.py", line 242, in _get_abstract_dist_for
    self.require_hashes
  File "/cvmfs/sft.cern.ch/lcg/views/LCG_98python3/x86_64-centos7-gcc9-opt/lib/python3.7/site-packages/pip/_internal/operations/prepare.py", line 362, in prepare_linked_requirement
    abstract_dist.prep_for_dist(finder, self.build_isolation)
  File "/cvmfs/sft.cern.ch/lcg/views/LCG_98python3/x86_64-centos7-gcc9-opt/lib/python3.7/site-packages/pip/_internal/operations/prepare.py", line 138, in prep_for_dist
    self.req.load_pyproject_toml()
  File "/cvmfs/sft.cern.ch/lcg/views/LCG_98python3/x86_64-centos7-gcc9-opt/lib/python3.7/site-packages/pip/_internal/req/req_install.py", line 492, in load_pyproject_toml
    str(self)
  File "/cvmfs/sft.cern.ch/lcg/views/LCG_98python3/x86_64-centos7-gcc9-opt/lib/python3.7/site-packages/pip/_internal/pyproject.py", line 66, in load_pyproject_toml
    pp_toml = pytoml.load(f)
  File "/cvmfs/sft.cern.ch/lcg/views/LCG_98python3/x86_64-centos7-gcc9-opt/lib/python3.7/site-packages/pip/_vendor/pytoml/parser.py", line 11, in load
    return loads(fin.read(), translate=translate, object_pairs_hook=object_pairs_hook, filename=getattr(fin, 'name', repr(fin)))
  File "/cvmfs/sft.cern.ch/lcg/views/LCG_98python3/x86_64-centos7-gcc9-opt/lib/python3.7/site-packages/pip/_vendor/pytoml/parser.py", line 24, in loads
    ast = _p_toml(src, object_pairs_hook=object_pairs_hook)
  File "/cvmfs/sft.cern.ch/lcg/views/LCG_98python3/x86_64-centos7-gcc9-opt/lib/python3.7/site-packages/pip/_vendor/pytoml/parser.py", line 340, in _p_toml
    s.expect_eof()
  File "/cvmfs/sft.cern.ch/lcg/views/LCG_98python3/x86_64-centos7-gcc9-opt/lib/python3.7/site-packages/pip/_vendor/pytoml/parser.py", line 125, in expect_eof
    return self._expect(self.consume_eof())
  File "/cvmfs/sft.cern.ch/lcg/views/LCG_98python3/x86_64-centos7-gcc9-opt/lib/python3.7/site-packages/pip/_vendor/pytoml/parser.py", line 165, in _expect
    raise TomlError('msg', self._pos[0], self._pos[1], self._filename)
pip._vendor.pytoml.core.TomlError: /tmp/pip-install-9hg8lp9v/awkward/pyproject.toml(82, 1): msg
```

**Comment by lgray** [comment]
Can you try this with a newer LCG release, or are you pinned to a particular one? This error (which is an error in awkward array, rather than coffea) looks like some out-of-date-ness in pip or other baseline packages.

@jpivarski @agoose77

**Comment by rdelliga** [comment]
I tried to upgrade pip and it worked. Thank you for your help.
