### ISSUE TITLE
Nanovents not working with awkward 2.4.5

### ISSUE THREAD

**Issue by nikoladze** [scikit-hep/coffea#906]
When i try to produce a nanoevents object and have awkward 2.4.5 installed and run

```python
from coffea.nanoevents import NanoEventsFactory, NanoAODSchema
factory = NanoEventsFactory.from_root(
    {"tests/samples/nano_dy.root": "Events"},
    schemaclass=NanoAODSchema,
    permit_dask=True,
)
events = factory.events()
print(events.Jet.pt.compute())
```
I get the following exception

<details>

```python
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/nikolai/venv/dask-awkward/lib/python3.11/site-packages/dask/base.py", line 342, in compute
    (result,) = compute(self, traverse=False, **kwargs)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/nikolai/venv/dask-awkward/lib/python3.11/site-packages/dask/base.py", line 628, in compute
    results = schedule(dsk, keys, **kwargs)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/nikolai/venv/dask-awkward/lib/python3.11/site-packages/uproot/_dask.py", line 912, in __call__
    layout = awkward.from_buffers(
             ^^^^^^^^^^^^^^^^^^^^^
  File "/home/nikolai/venv/dask-awkward/lib/python3.11/site-packages/awkward/_dispatch.py", line 37, in dispatch
    gen_or_result = func(*args, **kwargs)
                    ^^^^^^^^^^^^^^^^^^^^^
  File "/home/nikolai/venv/dask-awkward/lib/python3.11/site-packages/awkward/operations/ak_from_buffers.py", line 97, in from_buffers
    return _impl(
           ^^^^^^
  File "/home/nikolai/venv/dask-awkward/lib/python3.11/site-packages/awkward/operations/ak_from_buffers.py", line 141, in _impl
    out = _reconstitute(form, length, container, getkey, backend, byteorder, simplify)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/nikolai/venv/dask-awkward/lib/python3.11/site-packages/awkward/operations/ak_from_buffers.py", line 394, in _reconstitute
    contents = [
               ^
  File "/home/nikolai/venv/dask-awkward/lib/python3.11/site-packages/awkward/operations/ak_from_buffers.py", line 395, in <listcomp>
    _reconstitute(
  File "/home/nikolai/venv/dask-awkward/lib/python3.11/site-packages/awkward/operations/ak_from_buffers.py", line 372, in _reconstitute
    content = _reconstitute(
              ^^^^^^^^^^^^^^
  File "/home/nikolai/venv/dask-awkward/lib/python3.11/site-packages/awkward/operations/ak_from_buffers.py", line 394, in _reconstitute
    contents = [
               ^
  File "/home/nikolai/venv/dask-awkward/lib/python3.11/site-packages/awkward/operations/ak_from_buffers.py", line 395, in <listcomp>
    _reconstitute(
  File "/home/nikolai/venv/dask-awkward/lib/python3.11/site-packages/awkward/operations/ak_from_buffers.py", line 186, in _reconstitute
    raw_array = container[getkey(form, "data")]
                ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^
  File "/home/nikolai/code/coffea/src/coffea/nanoevents/mapping/base.py", line 115, in __getitem__
    out = numpy.array(out)
          ^^^^^^^^^^^^^^^^
  File "/home/nikolai/venv/dask-awkward/lib/python3.11/site-packages/awkward/contents/content.py", line 293, in __array__
    raise TypeError(
TypeError: do not try to convert low-level layouts (Content subclasses) into NumPy arrays; put them in ak.highlevel.Array

This error occurred while calling

    ak.from_buffers(
        RecordForm-instance
        40
        <coffea.nanoevents.mapping.uproot.UprootSourceMapping object at 0x7fc...
        buffer_key = partial-instance
        highlevel = False
    )
```

</details>

This seems to be due to the changes in scikit-hep/awkward#2370 - awkward now doesn't like `np.array` to be called on layouts anymore. Maybe it's enough to change this line

https://github.com/CoffeaTeam/coffea/blob/1aa0fbda948d945eaa3406b5f68775aca3334ca3/src/coffea/nanoevents/mapping/base.py#L115

To something like

```python
out = np.array(ak.Array(out))
```

but i'm not entirely sure about other consequences of this or if there is some deeper thing that should be changed.

**Comment by lgray** [comment]
You need to merge https://github.com/CoffeaTeam/coffea/pull/900 into your local coffea.

There were backwards incompatible changes in awkward/dask-awkward/dask-histogram/uproot from awkward 2.4.5. 
The PR above moves the appropriate pins and adapts coffea to use the new and more robust column optimization.

It's a definite improvement!

**Comment by lgray** [comment]
Doing so solves this on my laptop, closing issue for now. Please reopen if something else doesn't work!
